// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineMeterGroupComponent } from '@tylertech/forge';

import { ForgeMeterModule } from '../meter/meter.module';
import { MeterGroupComponent } from './meter-group.component';

@NgModule({
  imports: [CommonModule, ForgeMeterModule],
  declarations: [MeterGroupComponent],
  exports: [MeterGroupComponent, ForgeMeterModule]
})
export class ForgeMeterGroupModule {
  constructor() {
    defineMeterGroupComponent();
  }
}
