// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RteStrikeComponent as RteStrikeComponentCustomElement, defineRteStrikeComponent } from '@tylertech/forge-rich-text-editor/features';

/**  */
@Component({
  selector: 'forge-rte-strike',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RteStrikeComponent {
  protected elementRef = inject<ElementRef<RteStrikeComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-strike element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the strikethrough button. */
  @Input()
  public set label(value: RteStrikeComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RteStrikeComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  public get extensions(): RteStrikeComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRteStrikeComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
