// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RteDividerComponent as RteDividerComponentCustomElement, defineRteDividerComponent } from '@tylertech/forge-rich-text-editor/features';

/**  */
@Component({
  selector: 'forge-rte-divider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RteDividerComponent {
  protected elementRef = inject<ElementRef<RteDividerComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-divider element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineRteDividerComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
