// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRteDividerComponent } from '@tylertech/forge-rich-text-editor/features';

import { RteDividerComponent } from './rte-divider.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RteDividerComponent],
  exports: [RteDividerComponent]
})
export class ForgeRteDividerModule {
  constructor() {
    defineRteDividerComponent();
  }
}
