// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineBreadcrumbComponent } from '@tylertech/forge';

import { ForgeBreadcrumbItemModule } from '../breadcrumb-item/breadcrumb-item.module';
import { ForgeBreadcrumbOverflowMenuModule } from '../breadcrumb-overflow-menu/breadcrumb-overflow-menu.module';
import { BreadcrumbComponent } from './breadcrumb.component';

@NgModule({
  imports: [CommonModule, ForgeBreadcrumbItemModule, ForgeBreadcrumbOverflowMenuModule],
  declarations: [BreadcrumbComponent],
  exports: [BreadcrumbComponent, ForgeBreadcrumbItemModule, ForgeBreadcrumbOverflowMenuModule]
})
export class ForgeBreadcrumbModule {
  constructor() {
    defineBreadcrumbComponent();
  }
}
