// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { BreadcrumbComponent as BreadcrumbComponentCustomElement, defineBreadcrumbComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-breadcrumb',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class BreadcrumbComponent {
  protected elementRef = inject<ElementRef<BreadcrumbComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-breadcrumb element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The font size of the breadcrumb. */
  @Input()
  public set density(value: BreadcrumbComponentCustomElement['density']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.density = value;
    });
  }
  public get density(): BreadcrumbComponentCustomElement['density'] {
    return this.nativeElement.density;
  }

  constructor() {
    defineBreadcrumbComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
