// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { BreadcrumbComponent as BreadcrumbComponentCustomElement, defineBreadcrumbComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-breadcrumb',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class BreadcrumbComponent {
  protected elementRef = inject<ElementRef<BreadcrumbComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-breadcrumb element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Controls whether scroll buttons are displayed when the items overflow their container. */
  @Input({ transform: booleanAttribute })
  public set scrollButtons(value: BreadcrumbComponentCustomElement['scrollButtons']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.scrollButtons = value;
    });
  }
  public get scrollButtons(): BreadcrumbComponentCustomElement['scrollButtons'] {
    return this.nativeElement.scrollButtons;
  }

  constructor() {
    defineBreadcrumbComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
