// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextContentComponent } from '@tylertech/forge-rich-text-editor';

import { RichTextContentComponent } from './rich-text-content.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextContentComponent],
  exports: [RichTextContentComponent]
})
export class ForgeRichTextContentModule {
  constructor() {
    defineRichTextContentComponent();
  }
}
