// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RichTextContentComponent as RichTextContentComponentCustomElement, defineRichTextContentComponent } from '@tylertech/forge-rich-text-editor';

/**  */
@Component({
  selector: 'forge-rich-text-content',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextContentComponent {
  protected elementRef = inject<ElementRef<RichTextContentComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rich-text-content element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineRichTextContentComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
