// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { BannerComponent as BannerComponentCustomElement, defineBannerComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-banner',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class BannerComponent {
  protected elementRef = inject<ElementRef<BannerComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-banner element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Controls the visibility of the banner. */
  @Input({ transform: booleanAttribute })
  public set dismissed(value: BannerComponentCustomElement['dismissed']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.dismissed = value;
    });
  }
  public get dismissed(): BannerComponentCustomElement['dismissed'] {
    return this.nativeElement.dismissed;
  }

  /** Controls the visibility of the built-in dismiss button. */
  @Input({ transform: booleanAttribute })
  public set persistent(value: BannerComponentCustomElement['persistent']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.persistent = value;
    });
  }
  public get persistent(): BannerComponentCustomElement['persistent'] {
    return this.nativeElement.persistent;
  }

  /** The theme of the banner. */
  @Input()
  public set theme(value: BannerComponentCustomElement['theme']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.theme = value;
    });
  }
  public get theme(): BannerComponentCustomElement['theme'] {
    return this.nativeElement.theme;
  }

  @Input({ transform: booleanAttribute })
  public set canDismiss(value: BannerComponentCustomElement['canDismiss']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.canDismiss = value;
    });
  }
  public get canDismiss(): BannerComponentCustomElement['canDismiss'] {
    return this.nativeElement.canDismiss;
  }

  constructor() {
    defineBannerComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
