// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextToolbarComponent } from '@tylertech/forge-rich-text-editor';

import { RichTextToolbarComponent } from './rich-text-toolbar.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextToolbarComponent],
  exports: [RichTextToolbarComponent]
})
export class ForgeRichTextToolbarModule {
  constructor() {
    defineRichTextToolbarComponent();
  }
}
