// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RichTextToolbarComponent as RichTextToolbarComponentCustomElement, defineRichTextToolbarComponent } from '@tylertech/forge-rich-text-editor';

/**  */
@Component({
  selector: 'forge-rich-text-toolbar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextToolbarComponent {
  protected elementRef = inject<ElementRef<RichTextToolbarComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rich-text-toolbar element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible name of the toolbar. */
  @Input()
  public set label(value: RichTextToolbarComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RichTextToolbarComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  constructor() {
    defineRichTextToolbarComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
