// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input, inject } from '@angular/core';
import { AppLayoutComponent as AppLayoutComponentCustomElement, defineAppLayoutComponent } from '@tylertech/forge/app-layout';

/**  */
@Component({
  selector: 'forge-app-layout',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AppLayoutComponent {
  protected elementRef = inject<ElementRef<AppLayoutComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-app-layout element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The title text to display in the app bar. */
  @Input()
  public set appTitle(value: AppLayoutComponentCustomElement['appTitle']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.appTitle = value;
    });
  }
  public get appTitle(): AppLayoutComponentCustomElement['appTitle'] {
    return this.nativeElement.appTitle;
  }

  /** The URL that the app bar title links to. */
  @Input()
  public set appTitleHref(value: AppLayoutComponentCustomElement['appTitleHref']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.appTitleHref = value;
    });
  }
  public get appTitleHref(): AppLayoutComponentCustomElement['appTitleHref'] {
    return this.nativeElement.appTitleHref;
  }

  /** The screen width breakpoint in pixels for responsive behavior. */
  @Input({ transform: numberAttribute })
  public set breakpoint(value: AppLayoutComponentCustomElement['breakpoint']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.breakpoint = value;
    });
  }
  public get breakpoint(): AppLayoutComponentCustomElement['breakpoint'] {
    return this.nativeElement.breakpoint;
  }

  /** Whether to use `forge-mini-drawer` instead of `forge-drawer` for large screens. */
  @Input({ transform: booleanAttribute })
  public set useMiniDrawer(value: AppLayoutComponentCustomElement['useMiniDrawer']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.useMiniDrawer = value;
    });
  }
  public get useMiniDrawer(): AppLayoutComponentCustomElement['useMiniDrawer'] {
    return this.nativeElement.useMiniDrawer;
  }

  /** Whether the mini drawer should expand on hover. */
  @Input({ transform: booleanAttribute })
  public set miniHover(value: AppLayoutComponentCustomElement['miniHover']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.miniHover = value;
    });
  }
  public get miniHover(): AppLayoutComponentCustomElement['miniHover'] {
    return this.nativeElement.miniHover;
  }

  /** Whether the current screen width is above the breakpoint. */
  public get isLargeScreen(): AppLayoutComponentCustomElement['isLargeScreen'] {
    return this.nativeElement.isLargeScreen;
  }

  /** Closes the navigation drawer. Only has effect on small screens where the drawer is modal. */
  public closeDrawer(...args: Parameters<AppLayoutComponentCustomElement['closeDrawer']>): ReturnType<AppLayoutComponentCustomElement['closeDrawer']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.closeDrawer(...args));
  }

  constructor() {
    defineAppLayoutComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
