// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineKbdComponent } from '@tylertech/forge';

import { KbdComponent } from './kbd.component';

@NgModule({
  imports: [CommonModule],
  declarations: [KbdComponent],
  exports: [KbdComponent]
})
export class ForgeKbdModule {
  constructor() {
    defineKbdComponent();
  }
}
