// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { KbdComponent as KbdComponentCustomElement, defineKbdComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-kbd',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class KbdComponent {
  protected elementRef = inject<ElementRef<KbdComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-kbd element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** An array of alphanumeric keys to display. */
  @Input()
  public set keys(value: KbdComponentCustomElement['keys']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.keys = value;
    });
  }
  public get keys(): KbdComponentCustomElement['keys'] {
    return this.nativeElement.keys;
  }

  /** Whether to display the Alt key (Option/⌥ on Apple keyboards or Alt on Windows keyboards). */
  @Input({ transform: booleanAttribute })
  public set alt(value: KbdComponentCustomElement['alt']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.alt = value;
    });
  }
  public get alt(): KbdComponentCustomElement['alt'] {
    return this.nativeElement.alt;
  }

  /** Whether to display the Control key (Control/⌃ on Apple keyboards or Ctrl on Windows keyboards). */
  @Input({ transform: booleanAttribute })
  public set ctrl(value: KbdComponentCustomElement['ctrl']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.ctrl = value;
    });
  }
  public get ctrl(): KbdComponentCustomElement['ctrl'] {
    return this.nativeElement.ctrl;
  }

  /** Whether to display the Meta key (Command/⌘ on Apple keyboards or ⊞ on Windows keyboards). */
  @Input({ transform: booleanAttribute })
  public set meta(value: KbdComponentCustomElement['meta']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.meta = value;
    });
  }
  public get meta(): KbdComponentCustomElement['meta'] {
    return this.nativeElement.meta;
  }

  /** Whether to display the Shift key. */
  @Input({ transform: booleanAttribute })
  public set shift(value: KbdComponentCustomElement['shift']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.shift = value;
    });
  }
  public get shift(): KbdComponentCustomElement['shift'] {
    return this.nativeElement.shift;
  }

  /** Whether to display the keys in compact style. */
  @Input({ transform: booleanAttribute })
  public set dense(value: KbdComponentCustomElement['dense']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.dense = value;
    });
  }
  public get dense(): KbdComponentCustomElement['dense'] {
    return this.nativeElement.dense;
  }

  /** The theme to apply to the keyboard keys. */
  @Input()
  public set theme(value: KbdComponentCustomElement['theme']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.theme = value;
    });
  }
  public get theme(): KbdComponentCustomElement['theme'] {
    return this.nativeElement.theme;
  }

  /** Renders the keys without outlines. */
  @Input({ transform: booleanAttribute })
  public set muted(value: KbdComponentCustomElement['muted']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.muted = value;
    });
  }
  public get muted(): KbdComponentCustomElement['muted'] {
    return this.nativeElement.muted;
  }

  constructor() {
    defineKbdComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
