// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAccordionComponent } from '@tylertech/forge';

import { ForgeExpansionPanelModule } from '../expansion-panel/expansion-panel.module';
import { AccordionComponent } from './accordion.component';

@NgModule({
  imports: [CommonModule, ForgeExpansionPanelModule],
  declarations: [AccordionComponent],
  exports: [AccordionComponent, ForgeExpansionPanelModule]
})
export class ForgeAccordionModule {
  constructor() {
    defineAccordionComponent();
  }
}
