// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAppBarSearchComponent } from '@tylertech/forge';

import { AppBarSearchComponent } from './app-bar-search.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AppBarSearchComponent],
  exports: [AppBarSearchComponent]
})
export class ForgeAppBarSearchModule {
  constructor() {
    defineAppBarSearchComponent();
  }
}
