// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { StackComponent as StackComponentCustomElement, defineStackComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-stack',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class StackComponent {
  protected elementRef = inject<ElementRef<StackComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-stack element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Controls the direction of the stack. */
  @Input({ transform: booleanAttribute })
  public set inline(value: StackComponentCustomElement['inline']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.inline = value;
    });
  }
  public get inline(): StackComponentCustomElement['inline'] {
    return this.nativeElement.inline;
  }

  /** Controls if items wrap to a new line in inline mode */
  @Input({ transform: booleanAttribute })
  public set wrap(value: StackComponentCustomElement['wrap']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.wrap = value;
    });
  }
  public get wrap(): StackComponentCustomElement['wrap'] {
    return this.nativeElement.wrap;
  }

  /** Controls if items stretch and take up the maximum amount of space */
  @Input({ transform: booleanAttribute })
  public set stretch(value: StackComponentCustomElement['stretch']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.stretch = value;
    });
  }
  public get stretch(): StackComponentCustomElement['stretch'] {
    return this.nativeElement.stretch;
  }

  /** Controls the gap between the children within the stack */
  @Input()
  public set gap(value: StackComponentCustomElement['gap']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.gap = value;
    });
  }
  public get gap(): StackComponentCustomElement['gap'] {
    return this.nativeElement.gap;
  }

  /** Controls the align-items property of a row or column */
  @Input()
  public set alignment(value: StackComponentCustomElement['alignment']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.alignment = value;
    });
  }
  public get alignment(): StackComponentCustomElement['alignment'] {
    return this.nativeElement.alignment;
  }

  /** Controls the justify-content property of a row or column */
  @Input()
  public set justify(value: StackComponentCustomElement['justify']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.justify = value;
    });
  }
  public get justify(): StackComponentCustomElement['justify'] {
    return this.nativeElement.justify;
  }

  constructor() {
    defineStackComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
