// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRteUndoRedoComponent } from '@tylertech/forge-rich-text-editor/features';

import { RteUndoRedoComponent } from './rte-undo-redo.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RteUndoRedoComponent],
  exports: [RteUndoRedoComponent]
})
export class ForgeRteUndoRedoModule {
  constructor() {
    defineRteUndoRedoComponent();
  }
}
