// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { OptionComponent as OptionComponentCustomElement, defineOptionComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-option',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class OptionComponent {
  protected elementRef = inject<ElementRef<OptionComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-option element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether the option is selected. __Applies only to declarative options.__ */
  @Input({ transform: booleanAttribute })
  public set selected(value: OptionComponentCustomElement['selected']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.selected = value;
    });
  }
  public get selected(): OptionComponentCustomElement['selected'] {
    return this.nativeElement.selected;
  }

  /** Sets the option's height to fit two lines of text. __Applies only to declarative options.__ */
  @Input({ transform: booleanAttribute })
  public set twoLine(value: OptionComponentCustomElement['twoLine']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.twoLine = value;
    });
  }
  public get twoLine(): OptionComponentCustomElement['twoLine'] {
    return this.nativeElement.twoLine;
  }

  /** Sets the option's height to fit three lines of text. __Applies only to declarative options.__ */
  @Input({ transform: booleanAttribute })
  public set threeLine(value: OptionComponentCustomElement['threeLine']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.threeLine = value;
    });
  }
  public get threeLine(): OptionComponentCustomElement['threeLine'] {
    return this.nativeElement.threeLine;
  }

  /** Whether the option uses a dense layout. __Applies only to declarative options.__ */
  @Input({ transform: booleanAttribute })
  public set dense(value: OptionComponentCustomElement['dense']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.dense = value;
    });
  }
  public get dense(): OptionComponentCustomElement['dense'] {
    return this.nativeElement.dense;
  }

  /** Whether the option is read only. __Applies only to declarative options.__ */
  @Input({ transform: booleanAttribute })
  public set readonly(value: OptionComponentCustomElement['readonly']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.readonly = value;
    });
  }
  public get readonly(): OptionComponentCustomElement['readonly'] {
    return this.nativeElement.readonly;
  }

  /** The value of the option used for form submission. */
  @Input()
  public set value(value: OptionComponentCustomElement['value']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.value = value;
    });
  }
  public get value(): OptionComponentCustomElement['value'] {
    return this.nativeElement.value;
  }

  /** The label text of the option. __Applies only to config-based options.__ */
  @Input()
  public set label(value: OptionComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): OptionComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  /** The secondary label text of the option. __Applies only to config-based options.__ */
  @Input()
  public set secondaryLabel(value: OptionComponentCustomElement['secondaryLabel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.secondaryLabel = value;
    });
  }
  public get secondaryLabel(): OptionComponentCustomElement['secondaryLabel'] {
    return this.nativeElement.secondaryLabel;
  }

  /** Whether the option is disabled. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: OptionComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): OptionComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Whether the option renders as a divider instead of a list item. __Applies only to config-based options.__ */
  @Input({ transform: booleanAttribute })
  public set divider(value: OptionComponentCustomElement['divider']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.divider = value;
    });
  }
  public get divider(): OptionComponentCustomElement['divider'] {
    return this.nativeElement.divider;
  }

  /** Classes set on the option. __Applies only to config-based options.__ */
  @Input()
  public set optionClass(value: OptionComponentCustomElement['optionClass']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.optionClass = value;
    });
  }
  public get optionClass(): OptionComponentCustomElement['optionClass'] {
    return this.nativeElement.optionClass;
  }

  /** The name of the option's leading icon. __Applies only to config-based options.__ */
  @Input()
  public set leadingIcon(value: OptionComponentCustomElement['leadingIcon']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.leadingIcon = value;
    });
  }
  public get leadingIcon(): OptionComponentCustomElement['leadingIcon'] {
    return this.nativeElement.leadingIcon;
  }

  /** Classes set on the option's leading icon. __Applies only to config-based options.__ */
  @Input()
  public set leadingIconClass(value: OptionComponentCustomElement['leadingIconClass']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.leadingIconClass = value;
    });
  }
  public get leadingIconClass(): OptionComponentCustomElement['leadingIconClass'] {
    return this.nativeElement.leadingIconClass;
  }

  /** The type of the option's leading icon, either "font" or "component". __Applies only to config-based options.__ */
  @Input()
  public set leadingIconType(value: OptionComponentCustomElement['leadingIconType']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.leadingIconType = value;
    });
  }
  public get leadingIconType(): OptionComponentCustomElement['leadingIconType'] {
    return this.nativeElement.leadingIconType;
  }

  /** Properties set on the leading icon component. __Applies only to config-based options.__ */
  @Input()
  public set leadingIconComponentProps(value: OptionComponentCustomElement['leadingIconComponentProps']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.leadingIconComponentProps = value;
    });
  }
  public get leadingIconComponentProps(): OptionComponentCustomElement['leadingIconComponentProps'] {
    return this.nativeElement.leadingIconComponentProps;
  }

  /** The name of the option's trailing icon. __Applies only to config-based options.__ */
  @Input()
  public set trailingIcon(value: OptionComponentCustomElement['trailingIcon']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.trailingIcon = value;
    });
  }
  public get trailingIcon(): OptionComponentCustomElement['trailingIcon'] {
    return this.nativeElement.trailingIcon;
  }

  /** Classes set on the option's trailing icon. __Applies only to config-based options.__ */
  @Input()
  public set trailingIconClass(value: OptionComponentCustomElement['trailingIconClass']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.trailingIconClass = value;
    });
  }
  public get trailingIconClass(): OptionComponentCustomElement['trailingIconClass'] {
    return this.nativeElement.trailingIconClass;
  }

  /** The type of the option's trailing icon, either "font" or "component". __Applies only to config-based options.__ */
  @Input()
  public set trailingIconType(value: OptionComponentCustomElement['trailingIconType']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.trailingIconType = value;
    });
  }
  public get trailingIconType(): OptionComponentCustomElement['trailingIconType'] {
    return this.nativeElement.trailingIconType;
  }

  /** Properties set on the trailing icon component. __Applies only to config-based options.__ */
  @Input()
  public set trailingIconComponentProps(value: OptionComponentCustomElement['trailingIconComponentProps']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.trailingIconComponentProps = value;
    });
  }
  public get trailingIconComponentProps(): OptionComponentCustomElement['trailingIconComponentProps'] {
    return this.nativeElement.trailingIconComponentProps;
  }

  /** A callback function that returns an element to render in the option's leading slot. __Applies only to config-based options.__ */
  @Input()
  public set leadingBuilder(value: OptionComponentCustomElement['leadingBuilder']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.leadingBuilder = value;
    });
  }
  public get leadingBuilder(): OptionComponentCustomElement['leadingBuilder'] {
    return this.nativeElement.leadingBuilder;
  }

  /** A callback function that returns an element to render in the option's trailing slot. __Applies only to config-based options.__ */
  @Input()
  public set trailingBuilder(value: OptionComponentCustomElement['trailingBuilder']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.trailingBuilder = value;
    });
  }
  public get trailingBuilder(): OptionComponentCustomElement['trailingBuilder'] {
    return this.nativeElement.trailingBuilder;
  }

  /**
   * Configuration options for an attached tooltip. Accepts a plain string via the `tooltip`
   * attribute (translated to `{ text: <value> }`), or an object via property assignment.
   * __Applies only to config-based options.__
   */
  @Input()
  public set tooltip(value: OptionComponentCustomElement['tooltip']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.tooltip = value;
    });
  }
  public get tooltip(): OptionComponentCustomElement['tooltip'] {
    return this.nativeElement.tooltip;
  }

  constructor() {
    defineOptionComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
