// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { IconButtonComponent as IconButtonComponentCustomElement, defineIconButtonComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-icon-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class IconButtonComponent {
  protected elementRef = inject<ElementRef<IconButtonComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-icon-button element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Gets/sets whether the icon button can be toggled. */
  @Input({ transform: booleanAttribute })
  public set toggle(value: IconButtonComponentCustomElement['toggle']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.toggle = value;
    });
  }
  public get toggle(): IconButtonComponentCustomElement['toggle'] {
    return this.nativeElement.toggle;
  }

  /** Gets/sets whether the toggle button is pressed. Only applies when `toggle` is `true`. */
  @Input({ transform: booleanAttribute })
  public set pressed(value: IconButtonComponentCustomElement['pressed']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.pressed = value;
    });
  }
  public get pressed(): IconButtonComponentCustomElement['pressed'] {
    return this.nativeElement.pressed;
  }

  /** Alias for `pressed` _(deprecated)_. Whether or not the toggle button is pressed. Only applies when `toggle` is `true`. */
  @Input({ transform: booleanAttribute })
  public set on(value: IconButtonComponentCustomElement['on']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.on = value;
    });
  }
  public get on(): IconButtonComponentCustomElement['on'] {
    return this.nativeElement.on;
  }

  /** Gets/sets the variant of the button. Valid values are `text`, `outlined`, `filled`, and `raised`. */
  @Input()
  public set variant(value: IconButtonComponentCustomElement['variant']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.variant = value;
    });
  }
  public get variant(): IconButtonComponentCustomElement['variant'] {
    return this.nativeElement.variant;
  }

  /** Gets/sets the theme of the button. Valid values are `text`, `outlined`, `filled`, and `raised`. */
  @Input()
  public set theme(value: IconButtonComponentCustomElement['theme']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.theme = value;
    });
  }
  public get theme(): IconButtonComponentCustomElement['theme'] {
    return this.nativeElement.theme;
  }

  /** Gets/sets the shape of the button. Valid values are `circular` and `squared`. */
  @Input()
  public set shape(value: IconButtonComponentCustomElement['shape']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.shape = value;
    });
  }
  public get shape(): IconButtonComponentCustomElement['shape'] {
    return this.nativeElement.shape;
  }

  /** Gets/sets the density of the button. Valid values are `small`, `medium`, and `large`. */
  @Input()
  public set density(value: IconButtonComponentCustomElement['density']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.density = value;
    });
  }
  public get density(): IconButtonComponentCustomElement['density'] {
    return this.nativeElement.density;
  }

  /** Gets/sets the type of button. */
  @Input()
  public set type(value: IconButtonComponentCustomElement['type']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.type = value;
    });
  }
  public get type(): IconButtonComponentCustomElement['type'] {
    return this.nativeElement.type;
  }

  /** Gets/sets whether the button is disabled. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: IconButtonComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): IconButtonComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Gets/sets whether the button is dense. */
  @Input({ transform: booleanAttribute })
  public set dense(value: IconButtonComponentCustomElement['dense']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.dense = value;
    });
  }
  public get dense(): IconButtonComponentCustomElement['dense'] {
    return this.nativeElement.dense;
  }

  /** Gets/sets whether to show a popover icon. */
  @Input({ transform: booleanAttribute })
  public set popoverIcon(value: IconButtonComponentCustomElement['popoverIcon']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.popoverIcon = value;
    });
  }
  public get popoverIcon(): IconButtonComponentCustomElement['popoverIcon'] {
    return this.nativeElement.popoverIcon;
  }

  /** Gets/sets the button name for form association. */
  @Input()
  public set name(value: IconButtonComponentCustomElement['name']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.name = value;
    });
  }
  public get name(): IconButtonComponentCustomElement['name'] {
    return this.nativeElement.name;
  }

  /** Gets/sets the button value for form submission. */
  @Input()
  public set value(value: IconButtonComponentCustomElement['value']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.value = value;
    });
  }
  public get value(): IconButtonComponentCustomElement['value'] {
    return this.nativeElement.value;
  }

  /** Indicates to the targeted element which action to take. */
  @Input()
  public set command(value: IconButtonComponentCustomElement['command']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.command = value;
    });
  }
  public get command(): IconButtonComponentCustomElement['command'] {
    return this.nativeElement.command;
  }

  /** Targets another element to be invoked. */
  @Input()
  public set commandFor(value: IconButtonComponentCustomElement['commandFor']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.commandFor = value;
    });
  }
  public get commandFor(): IconButtonComponentCustomElement['commandFor'] {
    return this.nativeElement.commandFor;
  }

  /** Targets another element to be invoked. */
  @Input()
  public set commandForElement(value: IconButtonComponentCustomElement['commandForElement']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.commandForElement = value;
    });
  }
  public get commandForElement(): IconButtonComponentCustomElement['commandForElement'] {
    return this.nativeElement.commandForElement;
  }

  public click(...args: Parameters<IconButtonComponentCustomElement['click']>): ReturnType<IconButtonComponentCustomElement['click']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.click(...args));
  }

  public focus(...args: Parameters<IconButtonComponentCustomElement['focus']>): ReturnType<IconButtonComponentCustomElement['focus']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.focus(...args));
  }

  constructor() {
    defineIconButtonComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
