// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineTreeComponent } from '@tylertech/forge';

import { ForgeTreeItemModule } from '../tree-item/tree-item.module';
import { TreeComponent } from './tree.component';

@NgModule({
  imports: [CommonModule, ForgeTreeItemModule],
  declarations: [TreeComponent],
  exports: [TreeComponent, ForgeTreeItemModule]
})
export class ForgeTreeModule {
  constructor() {
    defineTreeComponent();
  }
}
