// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { TreeComponent as TreeComponentCustomElement, defineTreeComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-tree',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class TreeComponent {
  protected elementRef = inject<ElementRef<TreeComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-tree element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether opening an item closes all other items. */
  @Input({ transform: booleanAttribute })
  public set accordion(value: TreeComponentCustomElement['accordion']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.accordion = value;
    });
  }
  public get accordion(): TreeComponentCustomElement['accordion'] {
    return this.nativeElement.accordion;
  }

  /** Toggles the rendering of indent lines showing hierarchy. */
  @Input({ transform: booleanAttribute })
  public set indentLines(value: TreeComponentCustomElement['indentLines']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.indentLines = value;
    });
  }
  public get indentLines(): TreeComponentCustomElement['indentLines'] {
    return this.nativeElement.indentLines;
  }

  /** How selecting tree items is handled. */
  @Input()
  public set mode(value: TreeComponentCustomElement['mode']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.mode = value;
    });
  }
  public get mode(): TreeComponentCustomElement['mode'] {
    return this.nativeElement.mode;
  }

  /** Whether focusing an item also selects it. This takes no effect when in multiple mode. */
  @Input({ transform: booleanAttribute })
  public set selectionFollowsFocus(value: TreeComponentCustomElement['selectionFollowsFocus']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.selectionFollowsFocus = value;
    });
  }
  public get selectionFollowsFocus(): TreeComponentCustomElement['selectionFollowsFocus'] {
    return this.nativeElement.selectionFollowsFocus;
  }

  /** Whether selecting items is disabled. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: TreeComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): TreeComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** The value of all selected items. */
  @Input()
  public set value(value: TreeComponentCustomElement['value']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.value = value;
    });
  }
  public get value(): TreeComponentCustomElement['value'] {
    return this.nativeElement.value;
  }

  constructor() {
    defineTreeComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
