// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineTableComponent } from '@tylertech/forge';

import { TableComponent } from './table.component';

@NgModule({
  imports: [CommonModule],
  declarations: [TableComponent],
  exports: [TableComponent]
})
export class ForgeTableModule {
  constructor() {
    defineTableComponent();
  }
}
