// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { TreeItemComponent as TreeItemComponentCustomElement, defineTreeItemComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-tree-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class TreeItemComponent {
  protected elementRef = inject<ElementRef<TreeItemComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-tree-item element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The value of the tree item. */
  @Input()
  public set value(value: TreeItemComponentCustomElement['value']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.value = value;
    });
  }
  public get value(): TreeItemComponentCustomElement['value'] {
    return this.nativeElement.value;
  }

  /** Whether the tree item is selected. */
  @Input({ transform: booleanAttribute })
  public set selected(value: TreeItemComponentCustomElement['selected']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.selected = value;
    });
  }
  public get selected(): TreeItemComponentCustomElement['selected'] {
    return this.nativeElement.selected;
  }

  /** Whether the tree item is expanded. */
  @Input({ transform: booleanAttribute })
  public set open(value: TreeItemComponentCustomElement['open']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.open = value;
    });
  }
  public get open(): TreeItemComponentCustomElement['open'] {
    return this.nativeElement.open;
  }

  /** Whether the tree item supports lazy loading. */
  @Input({ transform: booleanAttribute })
  public set lazy(value: TreeItemComponentCustomElement['lazy']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.lazy = value;
    });
  }
  public get lazy(): TreeItemComponentCustomElement['lazy'] {
    return this.nativeElement.lazy;
  }

  /** Whether the tree item is disabled. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: TreeItemComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): TreeItemComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Whether opening the tree item is disabled. */
  @Input({ transform: booleanAttribute })
  public set openDisabled(value: TreeItemComponentCustomElement['openDisabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.openDisabled = value;
    });
  }
  public get openDisabled(): TreeItemComponentCustomElement['openDisabled'] {
    return this.nativeElement.openDisabled;
  }

  /** The depth of the tree item within the tree's hierarchy. */
  public get level(): TreeItemComponentCustomElement['level'] {
    return this.nativeElement.level;
  }

  /** Whether the tree item has no child items. */
  public get leaf(): TreeItemComponentCustomElement['leaf'] {
    return this.nativeElement.leaf;
  }

  /** Whether the selected value is indeterminate. */
  public get indeterminate(): TreeItemComponentCustomElement['indeterminate'] {
    return this.nativeElement.indeterminate;
  }

  constructor() {
    defineTreeItemComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
