// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineTreeItemComponent } from '@tylertech/forge';

import { TreeItemComponent } from './tree-item.component';

@NgModule({
  imports: [CommonModule],
  declarations: [TreeItemComponent],
  exports: [TreeItemComponent]
})
export class ForgeTreeItemModule {
  constructor() {
    defineTreeItemComponent();
  }
}
