packages:
  - packages/*

catalog:
  '@custom-elements-manifest/analyzer': 0.10.4
  '@floating-ui/dom': ^1.7.5
  '@lit/context': ^1.1.6
  '@storybook/addon-a11y': ^9.1.7
  '@storybook/addon-docs': ^9.1.7
  '@storybook/addon-links': ^9.1.7
  '@storybook/addon-themes': ^9.1.7
  '@storybook/web-components-vite': ^9.1.7
  '@tylertech-eslint/eslint-plugin': ^4.0.0
  '@tylertech/stylelint-rules': ^5.1.2
  '@tylertech/tyler-icons': ^2.0.4
  '@types/node': ^24.10.4
  '@vueless/storybook-dark-mode': ^9.1.7
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  glob: ^13.0.0
  lit: ^3.3.2
  plop: ^4.0.2
  prettier: ^3.6.2
  sass: ~1.92.1
  storybook: ^9.1.7
  stylelint: ^16.26.1
  tslib: ^2.8.1
  vite: ^7.3.1
  vite-tsconfig-paths: ^6.0.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - esbuild
  - node-sass
  - rs-module-lexer
