// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineSkipLinkComponent } from '@tylertech/forge';

import { SkipLinkComponent } from './skip-link.component';

@NgModule({
  imports: [CommonModule],
  declarations: [SkipLinkComponent],
  exports: [SkipLinkComponent]
})
export class ForgeSkipLinkModule {
  constructor() {
    defineSkipLinkComponent();
  }
}
