// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineButtonToggleGroupComponent } from '@tylertech/forge';

import { ForgeButtonToggleProxyModule } from '../button-toggle/button-toggle-proxy.module';
import { ButtonToggleGroupComponent } from './button-toggle-group.component';

@NgModule({
  imports: [CommonModule, ForgeButtonToggleProxyModule],
  declarations: [ButtonToggleGroupComponent],
  exports: [ButtonToggleGroupComponent, ForgeButtonToggleProxyModule]
})
export class ForgeButtonToggleGroupModule {
  constructor() {
    defineButtonToggleGroupComponent();
  }
}
