// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineFieldComponent } from '@tylertech/forge';

import { FieldComponent } from './field.component';

@NgModule({
  imports: [CommonModule],
  declarations: [FieldComponent],
  exports: [FieldComponent]
})
export class ForgeFieldModule {
  constructor() {
    defineFieldComponent();
  }
}
