// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ListItemComponent as ListItemComponentCustomElement, defineListItemComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-list-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ListItemComponent {
  protected elementRef = inject<ElementRef<ListItemComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-list-item element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Applies the selected state to the list item. */
  @Input({ transform: booleanAttribute })
  public set selected(value: ListItemComponentCustomElement['selected']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.selected = value;
    });
  }
  public get selected(): ListItemComponentCustomElement['selected'] {
    return this.nativeElement.selected;
  }

  /** Applies the active state to the list item by emulating its focused state. */
  @Input({ transform: booleanAttribute })
  public set active(value: ListItemComponentCustomElement['active']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.active = value;
    });
  }
  public get active(): ListItemComponentCustomElement['active'] {
    return this.nativeElement.active;
  }

  /** The unique value of the list item. */
  @Input()
  public set value(value: ListItemComponentCustomElement['value']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.value = value;
    });
  }
  public get value(): ListItemComponentCustomElement['value'] {
    return this.nativeElement.value;
  }

  /** Applies the dense state to the list item. */
  @Input({ transform: booleanAttribute })
  public set dense(value: ListItemComponentCustomElement['dense']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.dense = value;
    });
  }
  public get dense(): ListItemComponentCustomElement['dense'] {
    return this.nativeElement.dense;
  }

  /** Applies the indented state by adding margin to the start of the list item. */
  @Input({ transform: booleanAttribute })
  public set indented(value: ListItemComponentCustomElement['indented']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.indented = value;
    });
  }
  public get indented(): ListItemComponentCustomElement['indented'] {
    return this.nativeElement.indented;
  }

  /** Sets the list item height to support at least two lines of text. */
  @Input({ transform: booleanAttribute })
  public set twoLine(value: ListItemComponentCustomElement['twoLine']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.twoLine = value;
    });
  }
  public get twoLine(): ListItemComponentCustomElement['twoLine'] {
    return this.nativeElement.twoLine;
  }

  /** Sets the list item height to support at least three lines of text. */
  @Input({ transform: booleanAttribute })
  public set threeLine(value: ListItemComponentCustomElement['threeLine']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.threeLine = value;
    });
  }
  public get threeLine(): ListItemComponentCustomElement['threeLine'] {
    return this.nativeElement.threeLine;
  }

  /** Sets the list item to wrap its text content. */
  @Input({ transform: booleanAttribute })
  public set wrap(value: ListItemComponentCustomElement['wrap']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.wrap = value;
    });
  }
  public get wrap(): ListItemComponentCustomElement['wrap'] {
    return this.nativeElement.wrap;
  }

  /** Controls whether the list item will automatically attach itself to interactive slotted elements or not. */
  @Input({ transform: booleanAttribute })
  public set noninteractive(value: ListItemComponentCustomElement['noninteractive']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.noninteractive = value;
    });
  }
  public get noninteractive(): ListItemComponentCustomElement['noninteractive'] {
    return this.nativeElement.noninteractive;
  }

  /** Controls whether the interactive element will receive focus if a non-interactive element is clicked within the list item. */
  @Input({ transform: booleanAttribute })
  public set focusPropagation(value: ListItemComponentCustomElement['focusPropagation']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.focusPropagation = value;
    });
  }
  public get focusPropagation(): ListItemComponentCustomElement['focusPropagation'] {
    return this.nativeElement.focusPropagation;
  }

  constructor() {
    defineListItemComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
