// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAvatarComponent } from '@tylertech/forge';

import { AvatarComponent } from './avatar.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AvatarComponent],
  exports: [AvatarComponent]
})
export class ForgeAvatarModule {
  constructor() {
    defineAvatarComponent();
  }
}
