// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input, inject } from '@angular/core';
import { AvatarComponent as AvatarComponentCustomElement, defineAvatarComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-avatar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AvatarComponent {
  protected elementRef = inject<ElementRef<AvatarComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-avatar element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The text to display in the avatar. */
  @Input()
  public set text(value: AvatarComponentCustomElement['text']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.text = value;
    });
  }
  public get text(): AvatarComponentCustomElement['text'] {
    return this.nativeElement.text;
  }

  /** Controls the number of letters to display from the text. By default the text is split on spaces and the first character of each word is used. */
  @Input({ transform: numberAttribute })
  public set letterCount(value: AvatarComponentCustomElement['letterCount']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.letterCount = value;
    });
  }
  public get letterCount(): AvatarComponentCustomElement['letterCount'] {
    return this.nativeElement.letterCount;
  }

  /** The background image URL to use. */
  @Input()
  public set imageUrl(value: AvatarComponentCustomElement['imageUrl']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.imageUrl = value;
    });
  }
  public get imageUrl(): AvatarComponentCustomElement['imageUrl'] {
    return this.nativeElement.imageUrl;
  }

  constructor() {
    defineAvatarComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
