// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineContentScaffoldComponent } from '@tylertech/forge/content-scaffold';

import { ContentScaffoldComponent } from './content-scaffold.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ContentScaffoldComponent],
  exports: [ContentScaffoldComponent]
})
export class ForgeContentScaffoldModule {
  constructor() {
    defineContentScaffoldComponent();
  }
}
