// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ContentScaffoldComponent as ContentScaffoldComponentCustomElement, defineContentScaffoldComponent } from '@tylertech/forge/content-scaffold';

/**  */
@Component({
  selector: 'forge-content-scaffold',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ContentScaffoldComponent {
  protected elementRef = inject<ElementRef<ContentScaffoldComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-content-scaffold element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineContentScaffoldComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
