// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { StructuredCardComponent as StructuredCardComponentCustomElement, defineStructuredCardComponent } from '@tylertech/forge/structured-card';

/**  */
@Component({
  selector: 'forge-structured-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class StructuredCardComponent {
  protected elementRef = inject<ElementRef<StructuredCardComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-structured-card element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /**
   * Controls the semantic heading level for the title content. Defaults to `2` (h2).
   * Use this to maintain proper heading hierarchy in your document structure.
   */
  @Input()
  public set headingLevel(value: StructuredCardComponentCustomElement['headingLevel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.headingLevel = value;
    });
  }
  public get headingLevel(): StructuredCardComponentCustomElement['headingLevel'] {
    return this.nativeElement.headingLevel;
  }

  /**
   * Controls the spacing applied to the body section. Defaults to `default`.
   * - `default`: Applies standard padding to the body section.
   * - `none`: Removes padding from the body section for full-width content like tables.
   */
  @Input()
  public set bodySpacing(value: StructuredCardComponentCustomElement['bodySpacing']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.bodySpacing = value;
    });
  }
  public get bodySpacing(): StructuredCardComponentCustomElement['bodySpacing'] {
    return this.nativeElement.bodySpacing;
  }

  constructor() {
    defineStructuredCardComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
