// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineStructuredCardComponent } from '@tylertech/forge/structured-card';

import { StructuredCardComponent } from './structured-card.component';

@NgModule({
  imports: [CommonModule],
  declarations: [StructuredCardComponent],
  exports: [StructuredCardComponent]
})
export class ForgeStructuredCardModule {
  constructor() {
    defineStructuredCardComponent();
  }
}
