// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRteLinkComponent } from '@tylertech/forge-rich-text-editor/features';

import { RteLinkComponent } from './rte-link.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RteLinkComponent],
  exports: [RteLinkComponent]
})
export class ForgeRteLinkModule {
  constructor() {
    defineRteLinkComponent();
  }
}
