// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineCheckboxComponent } from '@tylertech/forge';

import { CheckboxComponent } from './checkbox.component';

@NgModule({
  imports: [CommonModule],
  declarations: [CheckboxComponent],
  exports: [CheckboxComponent]
})
export class ForgeCheckboxProxyModule {
  constructor() {
    defineCheckboxComponent();
  }
}
