// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineMenuComponent } from '@tylertech/forge';

import { MenuComponent } from './menu.component';

@NgModule({
  imports: [CommonModule],
  declarations: [MenuComponent],
  exports: [MenuComponent]
})
export class ForgeMenuModule {
  constructor() {
    defineMenuComponent();
  }
}
