// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAppBarMenuButtonComponent } from '@tylertech/forge';

import { AppBarMenuButtonComponent } from './app-bar-menu-button.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AppBarMenuButtonComponent],
  exports: [AppBarMenuButtonComponent]
})
export class ForgeAppBarMenuButtonModule {
  constructor() {
    defineAppBarMenuButtonComponent();
  }
}
