// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ButtonAreaComponent as ButtonAreaComponentCustomElement, defineButtonAreaComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-button-area',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ButtonAreaComponent {
  protected elementRef = inject<ElementRef<ButtonAreaComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-button-area element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Controls whether the component and associated button element are disabled. This has no effect when the button area is used with an anchor element. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: ButtonAreaComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): ButtonAreaComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** The ID of a button or anchor element to use for semantics and functionality. */
  @Input()
  public set target(value: ButtonAreaComponentCustomElement['target']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.target = value;
    });
  }
  public get target(): ButtonAreaComponentCustomElement['target'] {
    return this.nativeElement.target;
  }

  /** A button or anchor element instance to use for semantics and functionality. */
  @Input()
  public set targetElement(value: ButtonAreaComponentCustomElement['targetElement']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.targetElement = value;
    });
  }
  public get targetElement(): ButtonAreaComponentCustomElement['targetElement'] {
    return this.nativeElement.targetElement;
  }

  constructor() {
    defineButtonAreaComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
