// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineButtonAreaComponent } from '@tylertech/forge';

import { ButtonAreaComponent } from './button-area.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ButtonAreaComponent],
  exports: [ButtonAreaComponent]
})
export class ForgeButtonAreaModule {
  constructor() {
    defineButtonAreaComponent();
  }
}
