// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { definePageStateComponent } from '@tylertech/forge';

import { PageStateComponent } from './page-state.component';

@NgModule({
  imports: [CommonModule],
  declarations: [PageStateComponent],
  exports: [PageStateComponent]
})
export class ForgePageStateModule {
  constructor() {
    definePageStateComponent();
  }
}
