// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAppBarComponent } from '@tylertech/forge';

import { AppBarComponent } from './app-bar.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AppBarComponent],
  exports: [AppBarComponent]
})
export class ForgeAppBarProxyModule {
  constructor() {
    defineAppBarComponent();
  }
}
