// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { AppBarComponent as AppBarComponentCustomElement, defineAppBarComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-app-bar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AppBarComponent {
  protected elementRef = inject<ElementRef<AppBarComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-app-bar element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The text to display in the title. */
  @Input()
  public set titleText(value: AppBarComponentCustomElement['titleText']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.titleText = value;
    });
  }
  public get titleText(): AppBarComponentCustomElement['titleText'] {
    return this.nativeElement.titleText;
  }

  /** The elevation of the app bar. */
  @Input()
  public set elevation(value: AppBarComponentCustomElement['elevation']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.elevation = value;
    });
  }
  public get elevation(): AppBarComponentCustomElement['elevation'] {
    return this.nativeElement.elevation;
  }

  /** The theme of the app bar. */
  @Input()
  public set theme(value: AppBarComponentCustomElement['theme']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.theme = value;
    });
  }
  public get theme(): AppBarComponentCustomElement['theme'] {
    return this.nativeElement.theme;
  }

  /** The href that will be used to make the logo and title area a clickable link. */
  @Input()
  public set href(value: AppBarComponentCustomElement['href']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.href = value;
    });
  }
  public get href(): AppBarComponentCustomElement['href'] {
    return this.nativeElement.href;
  }

  /** The `<a>` target of the logo + title area link when `href` is set. */
  @Input()
  public set target(value: AppBarComponentCustomElement['target']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.target = value;
    });
  }
  public get target(): AppBarComponentCustomElement['target'] {
    return this.nativeElement.target;
  }

  /** Controls how the theme is applied. `inherit` will apply the global theme to the app bar and all child components. `scoped` will only apply the theme to the app bar and not set any global tokens. */
  @Input()
  public set themeMode(value: AppBarComponentCustomElement['themeMode']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.themeMode = value;
    });
  }
  public get themeMode(): AppBarComponentCustomElement['themeMode'] {
    return this.nativeElement.themeMode;
  }

  constructor() {
    defineAppBarComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
