import { defineComponents, IconRegistry } from '@tylertech/forge';
import '@tylertech/forge-extended/app-layout';
import '@tylertech/forge-extended/user-profile';
import '@tylertech/forge-extended/structured-card';
import '@tylertech/forge-extended/count-card';

import {
  tylIconHome,
  tylIconNotifications,
  tylIconSettings,
  tylIconAccountCircle,
  tylIconDashboard,
  tylIconFolder,
  tylIconPeople,
  tylIconCalendarToday,
  tylIconChecklist,
  tylIconHelp,
  tylIconSupport,
  tylIconInbox,
  tylIconAdd,
  tylIconAddCircle,
  tylIconSend,
  tylIconDrafts,
  tylIconHistory,
  tylIconStar,
  tylIconTicket,
  tylIconAttachFile,
  tylIconVisibility,
  tylIconComment,
  tylIconForward,
  tylIconAdminPanelSettings,
  tylIconGroup,
  tylIconSecurity,
  tylIconPersonAdd,
  tylIconEmail,
  tylIconPhone,
  tylIconMoreVert,
  tylIconDelete,
  tylIconEdit,
  tylIconSave,
  tylIconBarChart,
  tylIconAttachMoney,
  tylIconShoppingCart,
  tylIconFilterList,
  tylIconDownload,
  tylIconCode,
  tylIconSearch,
  tylIconClose,
  tylIconNoteAdd,
  tylIconCableData,
  tylIconBook,
  tylIconChartArc,
  tylIconRateReview,
  tylIconRobot,
  tylIconCheckboxMarkedCircleOutline,
  tylIconCircleOutline
} from '@tylertech/tyler-icons';

// Register all Forge components
defineComponents();

// Register icons
IconRegistry.define([
  tylIconHome,
  tylIconNotifications,
  tylIconSettings,
  tylIconAccountCircle,
  tylIconDashboard,
  tylIconFolder,
  tylIconPeople,
  tylIconCalendarToday,
  tylIconChecklist,
  tylIconHelp,
  tylIconSupport,
  tylIconInbox,
  tylIconAdd,
  tylIconAddCircle,
  tylIconSend,
  tylIconDrafts,
  tylIconHistory,
  tylIconStar,
  tylIconTicket,
  tylIconAttachFile,
  tylIconVisibility,
  tylIconComment,
  tylIconForward,
  tylIconAdminPanelSettings,
  tylIconGroup,
  tylIconSecurity,
  tylIconPersonAdd,
  tylIconEmail,
  tylIconPhone,
  tylIconMoreVert,
  tylIconDelete,
  tylIconEdit,
  tylIconSave,
  tylIconBarChart,
  tylIconAttachMoney,
  tylIconShoppingCart,
  tylIconFilterList,
  tylIconDownload,
  tylIconCode,
  tylIconSearch,
  tylIconClose,
  tylIconNoteAdd,
  tylIconCableData,
  tylIconBook,
  tylIconChartArc,
  tylIconRateReview,
  tylIconRobot,
  tylIconCheckboxMarkedCircleOutline,
  tylIconCircleOutline
]);
