import { defineComponents, IconRegistry } from '@tylertech/forge';
import '@tylertech/forge/app-launcher';
import '@tylertech/forge/app-layout';
import '@tylertech/forge/busy-indicator';
import '@tylertech/forge/confirmation-dialog';
import '@tylertech/forge/count-card';
import '@tylertech/forge/footer';
import '@tylertech/forge/multi-select-header';
import '@tylertech/forge-extended/user-profile';
import '@tylertech/forge-extended/structured-card';

import {
  tylIconHome,
  tylIconNotifications,
  tylIconSettings,
  tylIconAccountCircle,
  tylIconDashboard,
  tylIconFolder,
  tylIconPeople,
  tylIconCalendarToday,
  tylIconChecklist,
  tylIconHelp,
  tylIconSupport,
  tylIconInbox,
  tylIconAdd,
  tylIconAddCircle,
  tylIconSend,
  tylIconDrafts,
  tylIconHistory,
  tylIconStar,
  tylIconTicket,
  tylIconAttachFile,
  tylIconVisibility,
  tylIconComment,
  tylIconForward,
  tylIconAdminPanelSettings,
  tylIconGroup,
  tylIconSecurity,
  tylIconPersonAdd,
  tylIconEmail,
  tylIconPhone,
  tylIconMoreVert,
  tylIconDelete,
  tylIconEdit,
  tylIconSave,
  tylIconBarChart,
  tylIconAttachMoney,
  tylIconShoppingCart,
  tylIconFilterList,
  tylIconDownload,
  tylIconCode,
  tylIconSearch,
  tylIconClose,
  tylIconNoteAdd,
  tylIconCableData,
  tylIconBook,
  tylIconChartArc,
  tylIconRateReview,
  tylIconRobot,
  tylIconCheckboxMarkedCircleOutline,
  tylIconCircleOutline,
  tylIconHomeCity,
  tylIconPayment,
  tylIconReceiptLong,
  tylIconFile,
  tylIconLicense,
  tylIconWater,
  tylIconTrashCan,
  tylIconMap,
  tylIconAccount,
  tylIconLocationCity,
  tylIconDirections,
  tylIconInfo,
  tylIconChevronDown,
  tylIconChevronRight,
  tylIconLibrary,
  tylIconGithub
} from '@tylertech/tyler-icons';

// Register all Forge components
defineComponents();

// Register icons
IconRegistry.define([
  tylIconHome,
  tylIconNotifications,
  tylIconSettings,
  tylIconAccountCircle,
  tylIconDashboard,
  tylIconFolder,
  tylIconPeople,
  tylIconCalendarToday,
  tylIconChecklist,
  tylIconHelp,
  tylIconSupport,
  tylIconInbox,
  tylIconAdd,
  tylIconAddCircle,
  tylIconSend,
  tylIconDrafts,
  tylIconHistory,
  tylIconStar,
  tylIconTicket,
  tylIconAttachFile,
  tylIconVisibility,
  tylIconComment,
  tylIconForward,
  tylIconAdminPanelSettings,
  tylIconGroup,
  tylIconSecurity,
  tylIconPersonAdd,
  tylIconEmail,
  tylIconPhone,
  tylIconMoreVert,
  tylIconDelete,
  tylIconEdit,
  tylIconSave,
  tylIconBarChart,
  tylIconAttachMoney,
  tylIconShoppingCart,
  tylIconFilterList,
  tylIconDownload,
  tylIconCode,
  tylIconSearch,
  tylIconClose,
  tylIconNoteAdd,
  tylIconCableData,
  tylIconBook,
  tylIconChartArc,
  tylIconRateReview,
  tylIconRobot,
  tylIconCheckboxMarkedCircleOutline,
  tylIconCircleOutline,
  tylIconHomeCity,
  tylIconPayment,
  tylIconReceiptLong,
  tylIconFile,
  tylIconLicense,
  tylIconWater,
  tylIconTrashCan,
  tylIconMap,
  tylIconAccount,
  tylIconLocationCity,
  tylIconDirections,
  tylIconInfo,
  tylIconChevronDown,
  tylIconChevronRight,
  tylIconLibrary,
  tylIconGithub
]);
