// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineResponsiveToolbarComponent } from '@tylertech/forge/responsive-toolbar';

import { ResponsiveToolbarComponent } from './responsive-toolbar.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ResponsiveToolbarComponent],
  exports: [ResponsiveToolbarComponent]
})
export class ForgeResponsiveToolbarModule {
  constructor() {
    defineResponsiveToolbarComponent();
  }
}
