// This file is generated by @tylertech/forge-adapter-codegen. Any changes will be overwritten.
import { NgModule } from '@angular/core';

import { ForgeRichTextContentModule } from './rich-text-content';
import { ForgeRichTextContextModule } from './rich-text-context';
import { ForgeRichTextEditorModule } from './rich-text-editor';
import { ForgeRichTextRendererModule } from './rich-text-renderer';
import { ForgeRteAlignModule } from './rte-align';
import { ForgeRteBoldModule } from './rte-bold';
import { ForgeRteBulletListModule } from './rte-bullet-list';
import { ForgeRteCodeModule } from './rte-code';
import { ForgeRteDividerModule } from './rte-divider';
import { ForgeRteHeadingModule } from './rte-heading';
import { ForgeRteItalicModule } from './rte-italic';
import { ForgeRteLinkModule } from './rte-link';
import { ForgeRteOrderedListModule } from './rte-ordered-list';
import { ForgeRteStandardToolsModule } from './rte-standard-tools';
import { ForgeRteStrikeModule } from './rte-strike';
import { ForgeRteUnderlineModule } from './rte-underline';
import { ForgeRteUndoRedoModule } from './rte-undo-redo';
import { ForgeRteToolButtonModule } from './rte-tool-button';

const MODULES = [
  ForgeRichTextContentModule,
  ForgeRichTextContextModule,
  ForgeRichTextEditorModule,
  ForgeRichTextRendererModule,
  ForgeRteAlignModule,
  ForgeRteBoldModule,
  ForgeRteBulletListModule,
  ForgeRteCodeModule,
  ForgeRteDividerModule,
  ForgeRteHeadingModule,
  ForgeRteItalicModule,
  ForgeRteLinkModule,
  ForgeRteOrderedListModule,
  ForgeRteStandardToolsModule,
  ForgeRteStrikeModule,
  ForgeRteUnderlineModule,
  ForgeRteUndoRedoModule,
  ForgeRteToolButtonModule
];

/** Imports and exports every generated module in this package. */
@NgModule({
  imports: MODULES,
  exports: MODULES
})
export class ForgeRteModule {}
