// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineTimelineItemComponent } from '@tylertech/forge';

import { TimelineItemComponent } from './timeline-item.component';

@NgModule({
  imports: [CommonModule],
  declarations: [TimelineItemComponent],
  exports: [TimelineItemComponent]
})
export class ForgeTimelineItemModule {
  constructor() {
    defineTimelineItemComponent();
  }
}
