// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineSelectDropdownComponent } from '@tylertech/forge';

import { SelectDropdownComponent } from './select-dropdown.component';

@NgModule({
  imports: [CommonModule],
  declarations: [SelectDropdownComponent],
  exports: [SelectDropdownComponent]
})
export class ForgeSelectDropdownModule {
  constructor() {
    defineSelectDropdownComponent();
  }
}
