// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineDialogComponent } from '@tylertech/forge';

import { DialogComponent } from './dialog.component';

@NgModule({
  imports: [CommonModule],
  declarations: [DialogComponent],
  exports: [DialogComponent]
})
export class ForgeDialogModule {
  constructor() {
    defineDialogComponent();
  }
}
