// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineTimePickerComponent } from '@tylertech/forge';

import { TimePickerComponent } from './time-picker.component';

@NgModule({
  imports: [CommonModule],
  declarations: [TimePickerComponent],
  exports: [TimePickerComponent]
})
export class ForgeTimePickerProxyModule {
  constructor() {
    defineTimePickerComponent();
  }
}
