// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import {
  AppLauncherLinkComponent as AppLauncherLinkComponentCustomElement,
  defineAppLauncherLinkComponent
} from '@tylertech/forge/app-launcher/app-launcher-link';

/**  */
@Component({
  selector: 'forge-app-launcher-link',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AppLauncherLinkComponent {
  protected elementRef = inject<ElementRef<AppLauncherLinkComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-app-launcher-link element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineAppLauncherLinkComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
