// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAppLauncherLinkComponent } from '@tylertech/forge/app-launcher/app-launcher-link';

import { AppLauncherLinkComponent } from './app-launcher-link.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AppLauncherLinkComponent],
  exports: [AppLauncherLinkComponent]
})
export class ForgeAppLauncherLinkModule {
  constructor() {
    defineAppLauncherLinkComponent();
  }
}
