// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RteCodeComponent as RteCodeComponentCustomElement, defineRteCodeComponent } from '@tylertech/forge-rich-text-editor/features';

/**  */
@Component({
  selector: 'forge-rte-code',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RteCodeComponent {
  protected elementRef = inject<ElementRef<RteCodeComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-code element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the code button. */
  @Input()
  public set label(value: RteCodeComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RteCodeComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  public get extensions(): RteCodeComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRteCodeComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
