// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineInlineMessageComponent } from '@tylertech/forge';

import { InlineMessageComponent } from './inline-message.component';

@NgModule({
  imports: [CommonModule],
  declarations: [InlineMessageComponent],
  exports: [InlineMessageComponent]
})
export class ForgeInlineMessageModule {
  constructor() {
    defineInlineMessageComponent();
  }
}
