// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineDrawerComponent } from '@tylertech/forge';

import { DrawerComponent } from './drawer.component';

@NgModule({
  imports: [CommonModule],
  declarations: [DrawerComponent],
  exports: [DrawerComponent]
})
export class ForgeDrawerModule {
  constructor() {
    defineDrawerComponent();
  }
}
