// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { BackdropComponent as BackdropComponentCustomElement, defineBackdropComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-backdrop',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class BackdropComponent {
  protected elementRef = inject<ElementRef<BackdropComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-backdrop element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether the backdrop is visible. */
  @Input({ transform: booleanAttribute })
  public set visible(value: BackdropComponentCustomElement['visible']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.visible = value;
    });
  }
  public get visible(): BackdropComponentCustomElement['visible'] {
    return this.nativeElement.visible;
  }

  /** Whether the backdrop uses "fixed" or "relative" positioning. */
  @Input({ transform: booleanAttribute })
  public set fixed(value: BackdropComponentCustomElement['fixed']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.fixed = value;
    });
  }
  public get fixed(): BackdropComponentCustomElement['fixed'] {
    return this.nativeElement.fixed;
  }

  /** Immediately shows the backdrop by setting the `visibility` to `true` without animations. */
  public show(...args: Parameters<BackdropComponentCustomElement['show']>): ReturnType<BackdropComponentCustomElement['show']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.show(...args));
  }

  /** Immediately hides the backdrop by setting the `visibility` to `false` without animations. */
  public hide(...args: Parameters<BackdropComponentCustomElement['hide']>): ReturnType<BackdropComponentCustomElement['hide']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.hide(...args));
  }

  /** Sets the `visibility` to `true` and animates in. */
  public fadeIn(...args: Parameters<BackdropComponentCustomElement['fadeIn']>): ReturnType<BackdropComponentCustomElement['fadeIn']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.fadeIn(...args));
  }

  /** Sets the `visibility` to `false` and animates out. */
  public fadeOut(...args: Parameters<BackdropComponentCustomElement['fadeOut']>): ReturnType<BackdropComponentCustomElement['fadeOut']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.fadeOut(...args));
  }

  constructor() {
    defineBackdropComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
