// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineBackdropComponent } from '@tylertech/forge';

import { BackdropComponent } from './backdrop.component';

@NgModule({
  imports: [CommonModule],
  declarations: [BackdropComponent],
  exports: [BackdropComponent]
})
export class ForgeBackdropModule {
  constructor() {
    defineBackdropComponent();
  }
}
