name: Bug Report
description: Report a bug
labels: ["bug", "needs triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - forge
        - forge-core
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 3.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, or other relevant info
      placeholder: e.g. Chrome 120, Windows 11
    validations:
      required: false
