name: Feature Request
description: Suggest a feature or new component
labels: ["enhancement", "needs triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - forge
        - forge-core
        - New package
        - Other
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New component
        - Enhancement to existing component
        - Other feature
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you want and why?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this be used?
    validations:
      required: false
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to contribute this
