// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineModalDrawerComponent } from '@tylertech/forge';

import { ModalDrawerComponent } from './modal-drawer.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ModalDrawerComponent],
  exports: [ModalDrawerComponent]
})
export class ForgeModalDrawerModule {
  constructor() {
    defineModalDrawerComponent();
  }
}
