// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input, inject } from '@angular/core';
import { FooterComponent as FooterComponentCustomElement, defineFooterComponent } from '@tylertech/forge/footer';

/**  */
@Component({
  selector: 'forge-footer',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class FooterComponent {
  protected elementRef = inject<ElementRef<FooterComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-footer element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Defines the footer layout mode. */
  @Input()
  public set layout(value: FooterComponentCustomElement['layout']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.layout = value;
    });
  }
  public get layout(): FooterComponentCustomElement['layout'] {
    return this.nativeElement.layout;
  }

  /** Width breakpoint in pixels used when layout is set to `auto`. */
  @Input({ transform: numberAttribute })
  public set layoutBreakpoint(value: FooterComponentCustomElement['layoutBreakpoint']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.layoutBreakpoint = value;
    });
  }
  public get layoutBreakpoint(): FooterComponentCustomElement['layoutBreakpoint'] {
    return this.nativeElement.layoutBreakpoint;
  }

  constructor() {
    defineFooterComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
