// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineFooterComponent } from '@tylertech/forge/footer';

import { ForgeFooterItemModule } from '../footer-item/footer-item.module';
import { FooterComponent } from './footer.component';

@NgModule({
  imports: [CommonModule, ForgeFooterItemModule],
  declarations: [FooterComponent],
  exports: [FooterComponent, ForgeFooterItemModule]
})
export class ForgeFooterModule {
  constructor() {
    defineFooterComponent();
  }
}
