/**
 * Shared utility functions for the Forge Blocks build system.
 * Contains file system helpers, CLI argument parsing, and category discovery.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { Category } from './types.js';

/**
 * Discovers block category directories within the blocks folder.
 * Categories are top-level directories that organize blocks by type.
 */
export function discoverCategories(blocksPath: string): Category[] {
  if (!fs.existsSync(blocksPath)) {
    return [];
  }

  const entries = fs.readdirSync(blocksPath, { withFileTypes: true });

  return entries
    .filter(entry => entry.isDirectory())
    .map(entry => ({
      name: entry.name,
      path: path.join(blocksPath, entry.name)
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Checks if a screenshot needs to be regenerated by comparing file modification times.
 * Returns true if the PNG doesn't exist or the HTML is newer than the PNG.
 */
export function needsScreenshot(htmlPath: string, pngPath: string): boolean {
  if (!fs.existsSync(pngPath)) {
    return true;
  }
  const htmlStat = fs.statSync(htmlPath);
  const pngStat = fs.statSync(pngPath);
  return htmlStat.mtimeMs > pngStat.mtimeMs;
}

/**
 * Gets a string value from CLI arguments by flag name.
 */
export function getArgValue(args: string[], flag: string): string | undefined {
  const index = args.indexOf(flag);
  return index !== -1 ? args[index + 1] : undefined;
}

/**
 * Gets a numeric value from CLI arguments by flag name.
 */
export function getArgNumber(args: string[], flag: string): number | undefined {
  const value = getArgValue(args, flag);
  return value !== undefined ? parseInt(value, 10) : undefined;
}

/**
 * Checks if a flag is present in CLI arguments.
 */
export function hasArg(args: string[], flag: string): boolean {
  return args.includes(flag);
}
