// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { TimelineBreakComponent as TimelineBreakComponentCustomElement, defineTimelineBreakComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-timeline-break',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class TimelineBreakComponent {
  protected elementRef = inject<ElementRef<TimelineBreakComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-timeline-break element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineTimelineBreakComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
