// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineTimelineBreakComponent } from '@tylertech/forge';

import { TimelineBreakComponent } from './timeline-break.component';

@NgModule({
  imports: [CommonModule],
  declarations: [TimelineBreakComponent],
  exports: [TimelineBreakComponent]
})
export class ForgeTimelineBreakModule {
  constructor() {
    defineTimelineBreakComponent();
  }
}
