// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { FooterItemComponent as FooterItemComponentCustomElement, defineFooterItemComponent } from '@tylertech/forge/footer/footer-item';

/**  */
@Component({
  selector: 'forge-footer-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class FooterItemComponent {
  protected elementRef = inject<ElementRef<FooterItemComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-footer-item element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineFooterItemComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
