// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { TabBarComponent as TabBarComponentCustomElement, defineTabBarComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-tab-bar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class TabBarComponent {
  protected elementRef = inject<ElementRef<TabBarComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-tab-bar element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /**
   * Sets the disabled state of all child tabs. If true, any new tabs added to the DOM will be
   * disabled by default. This can be used instead of setting individual tab disabled properties,
   * mixing the two methods of disabling is not supported. Disabled tabs remain focusable but are
   * not interactive.
   */
  @Input({ transform: booleanAttribute })
  public set disabled(value: TabBarComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): TabBarComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** The index of the active tab. */
  @Input()
  public set activeTab(value: TabBarComponentCustomElement['activeTab']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.activeTab = value;
    });
  }
  public get activeTab(): TabBarComponentCustomElement['activeTab'] {
    return this.nativeElement.activeTab;
  }

  /** The name of the active tab. */
  @Input()
  public set activeTabName(value: TabBarComponentCustomElement['activeTabName']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.activeTabName = value;
    });
  }
  public get activeTabName(): TabBarComponentCustomElement['activeTabName'] {
    return this.nativeElement.activeTabName;
  }

  /** Controls whether the tab bar is vertical or horizontal. */
  @Input({ transform: booleanAttribute })
  public set vertical(value: TabBarComponentCustomElement['vertical']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.vertical = value;
    });
  }
  public get vertical(): TabBarComponentCustomElement['vertical'] {
    return this.nativeElement.vertical;
  }

  /**
   * Controls whether the tabs stretch the full width of their container or cluster together at
   * their minimum width.
   */
  @Input({ transform: booleanAttribute })
  public set clustered(value: TabBarComponentCustomElement['clustered']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.clustered = value;
    });
  }
  public get clustered(): TabBarComponentCustomElement['clustered'] {
    return this.nativeElement.clustered;
  }

  /** Controls whether the tabs are taller to allow for slotted leading/trailing elements. */
  @Input({ transform: booleanAttribute })
  public set stacked(value: TabBarComponentCustomElement['stacked']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.stacked = value;
    });
  }
  public get stacked(): TabBarComponentCustomElement['stacked'] {
    return this.nativeElement.stacked;
  }

  /** Deprecated. Controls whether the tabs are styled as secondary tab navigation. */
  @Input({ transform: booleanAttribute })
  public set secondary(value: TabBarComponentCustomElement['secondary']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.secondary = value;
    });
  }
  public get secondary(): TabBarComponentCustomElement['secondary'] {
    return this.nativeElement.secondary;
  }

  /** Controls whether the tabs are rendered inverted (tab indicator at top instead of bottom). */
  @Input({ transform: booleanAttribute })
  public set inverted(value: TabBarComponentCustomElement['inverted']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.inverted = value;
    });
  }
  public get inverted(): TabBarComponentCustomElement['inverted'] {
    return this.nativeElement.inverted;
  }

  /** Controls whether the tabs can be closed with the delete key. */
  @Input({ transform: booleanAttribute })
  public set closable(value: TabBarComponentCustomElement['closable']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.closable = value;
    });
  }
  public get closable(): TabBarComponentCustomElement['closable'] {
    return this.nativeElement.closable;
  }

  /** Controls whether the tabs are automatically activated when receiving focus. */
  @Input({ transform: booleanAttribute })
  public set autoActivate(value: TabBarComponentCustomElement['autoActivate']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.autoActivate = value;
    });
  }
  public get autoActivate(): TabBarComponentCustomElement['autoActivate'] {
    return this.nativeElement.autoActivate;
  }

  /** Controls whether scroll buttons are displayed when the tabs overflow their container. */
  @Input({ transform: booleanAttribute })
  public set scrollButtons(value: TabBarComponentCustomElement['scrollButtons']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.scrollButtons = value;
    });
  }
  public get scrollButtons(): TabBarComponentCustomElement['scrollButtons'] {
    return this.nativeElement.scrollButtons;
  }

  /** The tab bar's theme. */
  @Input()
  public set theme(value: TabBarComponentCustomElement['theme']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.theme = value;
    });
  }
  public get theme(): TabBarComponentCustomElement['theme'] {
    return this.nativeElement.theme;
  }

  constructor() {
    defineTabBarComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
