// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineMultiSelectHeaderComponent } from '@tylertech/forge/multi-select-header';

import { MultiSelectHeaderComponent } from './multi-select-header.component';

@NgModule({
  imports: [CommonModule],
  declarations: [MultiSelectHeaderComponent],
  exports: [MultiSelectHeaderComponent]
})
export class ForgeMultiSelectHeaderModule {
  constructor() {
    defineMultiSelectHeaderComponent();
  }
}
