// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input, inject } from '@angular/core';
import { PaginatorComponent as PaginatorComponentCustomElement, definePaginatorComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-paginator',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class PaginatorComponent {
  protected elementRef = inject<ElementRef<PaginatorComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-paginator element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The zero-based page index. */
  @Input({ transform: numberAttribute })
  public set pageIndex(value: PaginatorComponentCustomElement['pageIndex']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.pageIndex = value;
    });
  }
  public get pageIndex(): PaginatorComponentCustomElement['pageIndex'] {
    return this.nativeElement.pageIndex;
  }

  /** Number of items to display on a page. */
  @Input({ transform: numberAttribute })
  public set pageSize(value: PaginatorComponentCustomElement['pageSize']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.pageSize = value;
    });
  }
  public get pageSize(): PaginatorComponentCustomElement['pageSize'] {
    return this.nativeElement.pageSize;
  }

  /** Sets page index by providing the number of items to skip. The getter for this property returns the number of items to skip. */
  @Input({ transform: numberAttribute })
  public set offset(value: PaginatorComponentCustomElement['offset']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.offset = value;
    });
  }
  public get offset(): PaginatorComponentCustomElement['offset'] {
    return this.nativeElement.offset;
  }

  /** The total number of items to be paginated. */
  @Input({ transform: numberAttribute })
  public set total(value: PaginatorComponentCustomElement['total']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.total = value;
    });
  }
  public get total(): PaginatorComponentCustomElement['total'] {
    return this.nativeElement.total;
  }

  /** The set of provided page size options to display to the user. */
  @Input()
  public set pageSizeOptions(value: PaginatorComponentCustomElement['pageSizeOptions']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.pageSizeOptions = value;
    });
  }
  public get pageSizeOptions(): PaginatorComponentCustomElement['pageSizeOptions'] {
    return this.nativeElement.pageSizeOptions;
  }

  /** A label for the paginator. */
  @Input()
  public set label(value: PaginatorComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): PaginatorComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  /** Whether to show the first page and last page buttons. */
  @Input({ transform: booleanAttribute })
  public set firstLast(value: PaginatorComponentCustomElement['firstLast']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.firstLast = value;
    });
  }
  public get firstLast(): PaginatorComponentCustomElement['firstLast'] {
    return this.nativeElement.firstLast;
  }

  /** Whether to show the first page button. Default is false. */
  @Input({ transform: booleanAttribute })
  public set first(value: PaginatorComponentCustomElement['first']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.first = value;
    });
  }
  public get first(): PaginatorComponentCustomElement['first'] {
    return this.nativeElement.first;
  }

  /** Whether the paginator is disabled. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: PaginatorComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): PaginatorComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Whether to use the alternative range label slot. */
  @Input({ transform: booleanAttribute })
  public set alternative(value: PaginatorComponentCustomElement['alternative']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.alternative = value;
    });
  }
  public get alternative(): PaginatorComponentCustomElement['alternative'] {
    return this.nativeElement.alternative;
  }

  /** A callback function to build the range label dynamically. */
  @Input()
  public set rangeLabelCallback(value: PaginatorComponentCustomElement['rangeLabelCallback']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.rangeLabelCallback = value;
    });
  }
  public get rangeLabelCallback(): PaginatorComponentCustomElement['rangeLabelCallback'] {
    return this.nativeElement.rangeLabelCallback;
  }

  /** Sets focus to the first focusable element within the paginator. */
  public focus(...args: Parameters<PaginatorComponentCustomElement['focus']>): ReturnType<PaginatorComponentCustomElement['focus']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.focus(...args));
  }

  /** Navigates to the first page. */
  public goToFirstPage(...args: Parameters<PaginatorComponentCustomElement['goToFirstPage']>): ReturnType<PaginatorComponentCustomElement['goToFirstPage']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.goToFirstPage(...args));
  }

  /** Navigates to the previous page. */
  public goToPreviousPage(
    ...args: Parameters<PaginatorComponentCustomElement['goToPreviousPage']>
  ): ReturnType<PaginatorComponentCustomElement['goToPreviousPage']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.goToPreviousPage(...args));
  }

  /** Navigates to the next page. */
  public goToNextPage(...args: Parameters<PaginatorComponentCustomElement['goToNextPage']>): ReturnType<PaginatorComponentCustomElement['goToNextPage']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.goToNextPage(...args));
  }

  /** Navigates to the last page. */
  public goToLastPage(...args: Parameters<PaginatorComponentCustomElement['goToLastPage']>): ReturnType<PaginatorComponentCustomElement['goToLastPage']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.goToLastPage(...args));
  }

  /** Checks if navigation to the first page is possible. */
  public canGoToFirstPage(
    ...args: Parameters<PaginatorComponentCustomElement['canGoToFirstPage']>
  ): ReturnType<PaginatorComponentCustomElement['canGoToFirstPage']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.canGoToFirstPage(...args));
  }

  /** Checks if navigation to the previous page is possible. */
  public canGoToPreviousPage(
    ...args: Parameters<PaginatorComponentCustomElement['canGoToPreviousPage']>
  ): ReturnType<PaginatorComponentCustomElement['canGoToPreviousPage']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.canGoToPreviousPage(...args));
  }

  /** Checks if navigation to the next page is possible. */
  public canGoToNextPage(
    ...args: Parameters<PaginatorComponentCustomElement['canGoToNextPage']>
  ): ReturnType<PaginatorComponentCustomElement['canGoToNextPage']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.canGoToNextPage(...args));
  }

  /** Checks if navigation to the last page is possible. */
  public canGoToLastPage(
    ...args: Parameters<PaginatorComponentCustomElement['canGoToLastPage']>
  ): ReturnType<PaginatorComponentCustomElement['canGoToLastPage']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.canGoToLastPage(...args));
  }

  constructor() {
    definePaginatorComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
