// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineBreadcrumbOverflowMenuComponent } from '@tylertech/forge';

import { BreadcrumbOverflowMenuComponent } from './breadcrumb-overflow-menu.component';

@NgModule({
  imports: [CommonModule],
  declarations: [BreadcrumbOverflowMenuComponent],
  exports: [BreadcrumbOverflowMenuComponent]
})
export class ForgeBreadcrumbOverflowMenuModule {
  constructor() {
    defineBreadcrumbOverflowMenuComponent();
  }
}
