// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineToolbarComponent } from '@tylertech/forge';

import { ToolbarComponent } from './toolbar.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ToolbarComponent],
  exports: [ToolbarComponent]
})
export class ForgeToolbarModule {
  constructor() {
    defineToolbarComponent();
  }
}
