// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineThemeToggleComponent } from '@tylertech/forge/theme-toggle';

import { ThemeToggleComponent } from './theme-toggle.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ThemeToggleComponent],
  exports: [ThemeToggleComponent]
})
export class ForgeThemeToggleModule {
  constructor() {
    defineThemeToggleComponent();
  }
}
