// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRteToolButtonComponent } from '@tylertech/forge-rich-text-editor/features';

import { RteToolButtonComponent } from './rte-tool-button.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RteToolButtonComponent],
  exports: [RteToolButtonComponent]
})
export class ForgeRteToolButtonModule {
  constructor() {
    defineRteToolButtonComponent();
  }
}
