// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { SecretComponent as SecretComponentCustomElement, defineSecretComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-secret',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class SecretComponent {
  protected elementRef = inject<ElementRef<SecretComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-secret element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether the secret content is visible. */
  @Input({ transform: booleanAttribute })
  public set open(value: SecretComponentCustomElement['open']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.open = value;
    });
  }
  public get open(): SecretComponentCustomElement['open'] {
    return this.nativeElement.open;
  }

  /** The style applied to hidden content when the secret is set to inline. Possible values are blur, masked, and noise. */
  @Input()
  public set variant(value: SecretComponentCustomElement['variant']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.variant = value;
    });
  }
  public get variant(): SecretComponentCustomElement['variant'] {
    return this.nativeElement.variant;
  }

  /** The mask pattern to use with the masked variant. When empty the slotted text content is used as the mask. */
  @Input()
  public set mask(value: SecretComponentCustomElement['mask']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.mask = value;
    });
  }
  public get mask(): SecretComponentCustomElement['mask'] {
    return this.nativeElement.mask;
  }

  /** The character to replace characters with in the masked variant. */
  @Input()
  public set maskCharacter(value: SecretComponentCustomElement['maskCharacter']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.maskCharacter = value;
    });
  }
  public get maskCharacter(): SecretComponentCustomElement['maskCharacter'] {
    return this.nativeElement.maskCharacter;
  }

  /** Characters that will not be replaced by the mask character in the masked variant. */
  @Input()
  public set unmaskedCharacters(value: SecretComponentCustomElement['unmaskedCharacters']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.unmaskedCharacters = value;
    });
  }
  public get unmaskedCharacters(): SecretComponentCustomElement['unmaskedCharacters'] {
    return this.nativeElement.unmaskedCharacters;
  }

  /** Whether the secret content should be displayed as a block element instead of inline with text. */
  @Input({ transform: booleanAttribute })
  public set block(value: SecretComponentCustomElement['block']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.block = value;
    });
  }
  public get block(): SecretComponentCustomElement['block'] {
    return this.nativeElement.block;
  }

  /** The position of the button when the secret is set to inline. Possible values are start and end. */
  @Input()
  public set buttonPosition(value: SecretComponentCustomElement['buttonPosition']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.buttonPosition = value;
    });
  }
  public get buttonPosition(): SecretComponentCustomElement['buttonPosition'] {
    return this.nativeElement.buttonPosition;
  }

  /** Whether to reveal content on hover/focus in addition to clicks. */
  @Input({ transform: booleanAttribute })
  public set showOnHover(value: SecretComponentCustomElement['showOnHover']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.showOnHover = value;
    });
  }
  public get showOnHover(): SecretComponentCustomElement['showOnHover'] {
    return this.nativeElement.showOnHover;
  }

  /** When set, secrets with the same name will close when another secret with that name is opened. */
  @Input()
  public set name(value: SecretComponentCustomElement['name']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.name = value;
    });
  }
  public get name(): SecretComponentCustomElement['name'] {
    return this.nativeElement.name;
  }

  constructor() {
    defineSecretComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
