// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineSecretComponent } from '@tylertech/forge';

import { SecretComponent } from './secret.component';

@NgModule({
  imports: [CommonModule],
  declarations: [SecretComponent],
  exports: [SecretComponent]
})
export class ForgeSecretModule {
  constructor() {
    defineSecretComponent();
  }
}
