// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { TimelineComponent as TimelineComponentCustomElement, defineTimelineComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-timeline',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class TimelineComponent {
  protected elementRef = inject<ElementRef<TimelineComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-timeline element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineTimelineComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
