// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RteBoldComponent as RteBoldComponentCustomElement, defineRteBoldComponent } from '@tylertech/forge-rich-text-editor/features';

/**  */
@Component({
  selector: 'forge-rte-bold',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RteBoldComponent {
  protected elementRef = inject<ElementRef<RteBoldComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-bold element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the bold button. */
  @Input()
  public set label(value: RteBoldComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RteBoldComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  public get extensions(): RteBoldComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRteBoldComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
