// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ProcessStepperComponent as ProcessStepperComponentCustomElement, defineProcessStepperComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-process-stepper',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ProcessStepperComponent {
  protected elementRef = inject<ElementRef<ProcessStepperComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-process-stepper element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The orientation of the process. */
  @Input()
  public set orientation(value: ProcessStepperComponentCustomElement['orientation']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.orientation = value;
    });
  }
  public get orientation(): ProcessStepperComponentCustomElement['orientation'] {
    return this.nativeElement.orientation;
  }

  /**
   * Whether each step displays its number within the marker. Steps with an icon marker, such as
   * completed and error steps, always show the icon instead.
   */
  @Input({ transform: booleanAttribute })
  public set numbered(value: ProcessStepperComponentCustomElement['numbered']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.numbered = value;
    });
  }
  public get numbered(): ProcessStepperComponentCustomElement['numbered'] {
    return this.nativeElement.numbered;
  }

  /**
   * Whether the steps are read-only indicators of progress. Steps in a read-only stepper do not
   * render a button or link, and cannot be activated.
   */
  @Input({ transform: booleanAttribute })
  public set readonly(value: ProcessStepperComponentCustomElement['readonly']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.readonly = value;
    });
  }
  public get readonly(): ProcessStepperComponentCustomElement['readonly'] {
    return this.nativeElement.readonly;
  }

  /** The steps within the process. */
  public get steps(): ProcessStepperComponentCustomElement['steps'] {
    return this.nativeElement.steps;
  }

  /** The step most recently activated by the user, or `null` if no step has been activated. */
  public get selectedStep(): ProcessStepperComponentCustomElement['selectedStep'] {
    return this.nativeElement.selectedStep;
  }

  /**
   * Whether the stepper has collapsed to its compact layout. A horizontal stepper in a container
   * narrower than 600px lays its steps out vertically, because there is not enough width for
   * legible step labels side by side.
   */
  public get compact(): ProcessStepperComponentCustomElement['compact'] {
    return this.nativeElement.compact;
  }

  /** The number of completed steps as a fraction of the total number of steps, between 0 and 1. */
  public get progress(): ProcessStepperComponentCustomElement['progress'] {
    return this.nativeElement.progress;
  }

  constructor() {
    defineProcessStepperComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
