// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineProcessStepperComponent } from '@tylertech/forge';

import { ForgeProcessStepModule } from '../process-step/process-step.module';
import { ProcessStepperComponent } from './process-stepper.component';

@NgModule({
  imports: [CommonModule, ForgeProcessStepModule],
  declarations: [ProcessStepperComponent],
  exports: [ProcessStepperComponent, ForgeProcessStepModule]
})
export class ForgeProcessStepperModule {
  constructor() {
    defineProcessStepperComponent();
  }
}
