// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineDateRangePickerComponent } from '@tylertech/forge';

import { DateRangePickerComponent } from './date-range-picker.component';

@NgModule({
  imports: [CommonModule],
  declarations: [DateRangePickerComponent],
  exports: [DateRangePickerComponent]
})
export class ForgeDateRangePickerProxyModule {
  constructor() {
    defineDateRangePickerComponent();
  }
}
