// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineKeyboardShortcutComponent } from '@tylertech/forge';

import { KeyboardShortcutComponent } from './keyboard-shortcut.component';

@NgModule({
  imports: [CommonModule],
  declarations: [KeyboardShortcutComponent],
  exports: [KeyboardShortcutComponent]
})
export class ForgeKeyboardShortcutModule {
  constructor() {
    defineKeyboardShortcutComponent();
  }
}
