// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { KeyboardShortcutComponent as KeyboardShortcutComponentCustomElement, defineKeyboardShortcutComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-keyboard-shortcut',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class KeyboardShortcutComponent {
  protected elementRef = inject<ElementRef<KeyboardShortcutComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-keyboard-shortcut element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Gets/sets the key binding. */
  @Input()
  public set key(value: KeyboardShortcutComponentCustomElement['key']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.key = value;
    });
  }
  public get key(): KeyboardShortcutComponentCustomElement['key'] {
    return this.nativeElement.key;
  }

  /** Alias for `key`. */
  @Input()
  public set keyBinding(value: KeyboardShortcutComponentCustomElement['keyBinding']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.keyBinding = value;
    });
  }
  public get keyBinding(): KeyboardShortcutComponentCustomElement['keyBinding'] {
    return this.nativeElement.keyBinding;
  }

  /** Gets/sets the id of the anchor element in the shortcut's root node. */
  @Input()
  public set anchor(value: KeyboardShortcutComponentCustomElement['anchor']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.anchor = value;
    });
  }
  public get anchor(): KeyboardShortcutComponentCustomElement['anchor'] {
    return this.nativeElement.anchor;
  }

  /** Gets/sets the name of an ancestor scope marker. */
  @Input()
  public set scope(value: KeyboardShortcutComponentCustomElement['scope']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.scope = value;
    });
  }
  public get scope(): KeyboardShortcutComponentCustomElement['scope'] {
    return this.nativeElement.scope;
  }

  /** Gets/sets the target element selector. */
  @Input()
  public set target(value: KeyboardShortcutComponentCustomElement['target']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.target = value;
    });
  }
  public get target(): KeyboardShortcutComponentCustomElement['target'] {
    return this.nativeElement.target;
  }

  /** Gets/sets the global listener state. */
  @Input({ transform: booleanAttribute })
  public set global(value: KeyboardShortcutComponentCustomElement['global']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.global = value;
    });
  }
  public get global(): KeyboardShortcutComponentCustomElement['global'] {
    return this.nativeElement.global;
  }

  /** Gets/sets whether the callback will be called while in a text entry field. */
  @Input({ transform: booleanAttribute })
  public set allowWhileTyping(value: KeyboardShortcutComponentCustomElement['allowWhileTyping']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.allowWhileTyping = value;
    });
  }
  public get allowWhileTyping(): KeyboardShortcutComponentCustomElement['allowWhileTyping'] {
    return this.nativeElement.allowWhileTyping;
  }

  /** Gets/sets whether held-key repeat events activate the shortcut. */
  @Input({ transform: booleanAttribute })
  public set allowRepeat(value: KeyboardShortcutComponentCustomElement['allowRepeat']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.allowRepeat = value;
    });
  }
  public get allowRepeat(): KeyboardShortcutComponentCustomElement['allowRepeat'] {
    return this.nativeElement.allowRepeat;
  }

  /** Gets/sets whether the shortcut allows outer scopes to also handle the key. */
  @Input({ transform: booleanAttribute })
  public set fallthrough(value: KeyboardShortcutComponentCustomElement['fallthrough']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.fallthrough = value;
    });
  }
  public get fallthrough(): KeyboardShortcutComponentCustomElement['fallthrough'] {
    return this.nativeElement.fallthrough;
  }

  /** Gets/sets whether to prevent default on keyboard events. */
  @Input({ transform: booleanAttribute })
  public set preventDefault(value: KeyboardShortcutComponentCustomElement['preventDefault']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.preventDefault = value;
    });
  }
  public get preventDefault(): KeyboardShortcutComponentCustomElement['preventDefault'] {
    return this.nativeElement.preventDefault;
  }

  /** Gets/sets whether to use capturing on keyboard events. */
  @Input({ transform: booleanAttribute })
  public set capture(value: KeyboardShortcutComponentCustomElement['capture']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.capture = value;
    });
  }
  public get capture(): KeyboardShortcutComponentCustomElement['capture'] {
    return this.nativeElement.capture;
  }

  /** Gets/sets whether to match codes instead of keys on keyboard events. */
  @Input({ transform: booleanAttribute })
  public set useCode(value: KeyboardShortcutComponentCustomElement['useCode']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.useCode = value;
    });
  }
  public get useCode(): KeyboardShortcutComponentCustomElement['useCode'] {
    return this.nativeElement.useCode;
  }

  /** Gets/sets whether the callback will be called. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: KeyboardShortcutComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): KeyboardShortcutComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Gets/sets whether aria-keyshortcuts is automatically set on the anchor. */
  @Input()
  public set anchorAccessibility(value: KeyboardShortcutComponentCustomElement['anchorAccessibility']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.anchorAccessibility = value;
    });
  }
  public get anchorAccessibility(): KeyboardShortcutComponentCustomElement['anchorAccessibility'] {
    return this.nativeElement.anchorAccessibility;
  }

  /** Gets/sets the activation callback. */
  @Input()
  public set activateCallback(value: KeyboardShortcutComponentCustomElement['activateCallback']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.activateCallback = value;
    });
  }
  public get activateCallback(): KeyboardShortcutComponentCustomElement['activateCallback'] {
    return this.nativeElement.activateCallback;
  }

  /** Gets/sets the anchor element directly. */
  @Input()
  public set anchorElement(value: KeyboardShortcutComponentCustomElement['anchorElement']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.anchorElement = value;
    });
  }
  public get anchorElement(): KeyboardShortcutComponentCustomElement['anchorElement'] {
    return this.nativeElement.anchorElement;
  }

  /** Gets/sets the scope element directly. */
  @Input()
  public set scopeElement(value: KeyboardShortcutComponentCustomElement['scopeElement']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.scopeElement = value;
    });
  }
  public get scopeElement(): KeyboardShortcutComponentCustomElement['scopeElement'] {
    return this.nativeElement.scopeElement;
  }

  constructor() {
    defineKeyboardShortcutComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
