// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineProfileCardComponent } from '@tylertech/forge';

import { ProfileCardComponent } from './profile-card.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ProfileCardComponent],
  exports: [ProfileCardComponent]
})
export class ForgeProfileCardModule {
  constructor() {
    defineProfileCardComponent();
  }
}
