// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input, inject } from '@angular/core';
import { AppBarProfileButtonComponent as AppBarProfileButtonComponentCustomElement, defineAppBarProfileButtonComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-app-bar-profile-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AppBarProfileButtonComponent {
  protected elementRef = inject<ElementRef<AppBarProfileButtonComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-app-bar-profile-button element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The full name. */
  @Input()
  public set fullName(value: AppBarProfileButtonComponentCustomElement['fullName']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.fullName = value;
    });
  }
  public get fullName(): AppBarProfileButtonComponentCustomElement['fullName'] {
    return this.nativeElement.fullName;
  }

  /** The email address. */
  @Input()
  public set email(value: AppBarProfileButtonComponentCustomElement['email']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.email = value;
    });
  }
  public get email(): AppBarProfileButtonComponentCustomElement['email'] {
    return this.nativeElement.email;
  }

  /** The url of the avatar image to display. */
  @Input()
  public set avatarImageUrl(value: AppBarProfileButtonComponentCustomElement['avatarImageUrl']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.avatarImageUrl = value;
    });
  }
  public get avatarImageUrl(): AppBarProfileButtonComponentCustomElement['avatarImageUrl'] {
    return this.nativeElement.avatarImageUrl;
  }

  /** The number of letters to display in the avatar. */
  @Input({ transform: numberAttribute })
  public set avatarLetterCount(value: AppBarProfileButtonComponentCustomElement['avatarLetterCount']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.avatarLetterCount = value;
    });
  }
  public get avatarLetterCount(): AppBarProfileButtonComponentCustomElement['avatarLetterCount'] {
    return this.nativeElement.avatarLetterCount;
  }

  /** The text to display in the avatar. */
  @Input()
  public set avatarText(value: AppBarProfileButtonComponentCustomElement['avatarText']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.avatarText = value;
    });
  }
  public get avatarText(): AppBarProfileButtonComponentCustomElement['avatarText'] {
    return this.nativeElement.avatarText;
  }

  /** The name of an alternative icon to display in the avatar. */
  @Input()
  public set avatarIcon(value: AppBarProfileButtonComponentCustomElement['avatarIcon']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.avatarIcon = value;
    });
  }
  public get avatarIcon(): AppBarProfileButtonComponentCustomElement['avatarIcon'] {
    return this.nativeElement.avatarIcon;
  }

  /** Whether to display the sign out button or not. Defaults to `true`. */
  @Input({ transform: booleanAttribute })
  public set signOutButton(value: AppBarProfileButtonComponentCustomElement['signOutButton']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.signOutButton = value;
    });
  }
  public get signOutButton(): AppBarProfileButtonComponentCustomElement['signOutButton'] {
    return this.nativeElement.signOutButton;
  }

  /** Whether to display the profile button or not. */
  @Input({ transform: booleanAttribute })
  public set profileButton(value: AppBarProfileButtonComponentCustomElement['profileButton']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.profileButton = value;
    });
  }
  public get profileButton(): AppBarProfileButtonComponentCustomElement['profileButton'] {
    return this.nativeElement.profileButton;
  }

  /** The text to display in the sign out button. */
  @Input()
  public set signOutButtonText(value: AppBarProfileButtonComponentCustomElement['signOutButtonText']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.signOutButtonText = value;
    });
  }
  public get signOutButtonText(): AppBarProfileButtonComponentCustomElement['signOutButtonText'] {
    return this.nativeElement.signOutButtonText;
  }

  /** The text to display in the profile button. */
  @Input()
  public set profileButtonText(value: AppBarProfileButtonComponentCustomElement['profileButtonText']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.profileButtonText = value;
    });
  }
  public get profileButtonText(): AppBarProfileButtonComponentCustomElement['profileButtonText'] {
    return this.nativeElement.profileButtonText;
  }

  /** Whether the profile card is open or not. */
  @Input({ transform: booleanAttribute })
  public set open(value: AppBarProfileButtonComponentCustomElement['open']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.open = value;
    });
  }
  public get open(): AppBarProfileButtonComponentCustomElement['open'] {
    return this.nativeElement.open;
  }

  /** The popup element when open. */
  public get popupElement(): AppBarProfileButtonComponentCustomElement['popupElement'] {
    return this.nativeElement.popupElement;
  }

  /** Sets the profile card builder callback that will be used to add extra content to the profile card. */
  @Input()
  public set profileCardBuilder(value: AppBarProfileButtonComponentCustomElement['profileCardBuilder']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.profileCardBuilder = value;
    });
  }
  public get profileCardBuilder(): AppBarProfileButtonComponentCustomElement['profileCardBuilder'] {
    return this.nativeElement.profileCardBuilder;
  }

  constructor() {
    defineAppBarProfileButtonComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
