// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAppBarProfileButtonComponent } from '@tylertech/forge';

import { AppBarProfileButtonComponent } from './app-bar-profile-button.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AppBarProfileButtonComponent],
  exports: [AppBarProfileButtonComponent]
})
export class ForgeAppBarProfileButtonModule {
  constructor() {
    defineAppBarProfileButtonComponent();
  }
}
