// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ExpansionPanelComponent as ExpansionPanelComponentCustomElement, defineExpansionPanelComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-expansion-panel',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ExpansionPanelComponent {
  protected elementRef = inject<ElementRef<ExpansionPanelComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-expansion-panel element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether the panel is open or closed. */
  @Input({ transform: booleanAttribute })
  public set open(value: ExpansionPanelComponentCustomElement['open']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.open = value;
    });
  }
  public get open(): ExpansionPanelComponentCustomElement['open'] {
    return this.nativeElement.open;
  }

  /** The orientation of the panel. */
  @Input()
  public set orientation(value: ExpansionPanelComponentCustomElement['orientation']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.orientation = value;
    });
  }
  public get orientation(): ExpansionPanelComponentCustomElement['orientation'] {
    return this.nativeElement.orientation;
  }

  /** The type of animation to use when opening/closing the panel. */
  @Input()
  public set animationType(value: ExpansionPanelComponentCustomElement['animationType']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.animationType = value;
    });
  }
  public get animationType(): ExpansionPanelComponentCustomElement['animationType'] {
    return this.nativeElement.animationType;
  }

  /** The id of the button that the expansion panel should be toggled by. */
  @Input()
  public set trigger(value: ExpansionPanelComponentCustomElement['trigger']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.trigger = value;
    });
  }
  public get trigger(): ExpansionPanelComponentCustomElement['trigger'] {
    return this.nativeElement.trigger;
  }

  /** The button that the expansion panel should be toggled by. */
  @Input()
  public set triggerElement(value: ExpansionPanelComponentCustomElement['triggerElement']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.triggerElement = value;
    });
  }
  public get triggerElement(): ExpansionPanelComponentCustomElement['triggerElement'] {
    return this.nativeElement.triggerElement;
  }

  /** The id of the `<forge-open-icon>` that the expansion panel should toggle. */
  @Input()
  public set openIcon(value: ExpansionPanelComponentCustomElement['openIcon']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.openIcon = value;
    });
  }
  public get openIcon(): ExpansionPanelComponentCustomElement['openIcon'] {
    return this.nativeElement.openIcon;
  }

  /** The `<forge-open-icon>` that the expansion panel should toggle. */
  @Input()
  public set openIconElement(value: ExpansionPanelComponentCustomElement['openIconElement']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.openIconElement = value;
    });
  }
  public get openIconElement(): ExpansionPanelComponentCustomElement['openIconElement'] {
    return this.nativeElement.openIconElement;
  }

  /** The expansion panel's name. Expansion panels that share the same name form an accordion group where only one panel may be open at a time. */
  @Input()
  public set name(value: ExpansionPanelComponentCustomElement['name']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.name = value;
    });
  }
  public get name(): ExpansionPanelComponentCustomElement['name'] {
    return this.nativeElement.name;
  }

  public toggle(...args: Parameters<ExpansionPanelComponentCustomElement['toggle']>): ReturnType<ExpansionPanelComponentCustomElement['toggle']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.toggle(...args));
  }

  constructor() {
    defineExpansionPanelComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
