// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineTabComponent } from '@tylertech/forge';

import { TabComponent } from './tab.component';

@NgModule({
  imports: [CommonModule],
  declarations: [TabComponent],
  exports: [TabComponent]
})
export class ForgeTabModule {
  constructor() {
    defineTabComponent();
  }
}
