// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { TabComponent as TabComponentCustomElement, defineTabComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-tab',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class TabComponent {
  protected elementRef = inject<ElementRef<TabComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-tab element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The name of the tab used for indexing and identication. */
  @Input()
  public set name(value: TabComponentCustomElement['name']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.name = value;
    });
  }
  public get name(): TabComponentCustomElement['name'] {
    return this.nativeElement.name;
  }

  /**
   * The disabled state of the tab. Disabled tabs remain focusable but are not interactive. Should
   * not be set if using the disabled property on `forge-tab-bar`.
   */
  @Input({ transform: booleanAttribute })
  public set disabled(value: TabComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): TabComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Whether the tab is the current active tab within its parent tab bar. */
  @Input({ transform: booleanAttribute })
  public set active(value: TabComponentCustomElement['active']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.active = value;
    });
  }
  public get active(): TabComponentCustomElement['active'] {
    return this.nativeElement.active;
  }

  /** The selected state of the tab. */
  @Input()
  public set selected(value: TabComponentCustomElement['selected']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.selected = value;
    });
  }
  public get selected(): TabComponentCustomElement['selected'] {
    return this.nativeElement.selected;
  }

  /** Controls whether the tab is vertical or horizontal. */
  @Input({ transform: booleanAttribute })
  public set vertical(value: TabComponentCustomElement['vertical']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.vertical = value;
    });
  }
  public get vertical(): TabComponentCustomElement['vertical'] {
    return this.nativeElement.vertical;
  }

  /** Controls whether the tab is taller to allow for slotted leading/trailing elements. */
  @Input({ transform: booleanAttribute })
  public set stacked(value: TabComponentCustomElement['stacked']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.stacked = value;
    });
  }
  public get stacked(): TabComponentCustomElement['stacked'] {
    return this.nativeElement.stacked;
  }

  /** Controls whether the tab is styled as secondary tab navigation. */
  @Input({ transform: booleanAttribute })
  public set secondary(value: TabComponentCustomElement['secondary']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.secondary = value;
    });
  }
  public get secondary(): TabComponentCustomElement['secondary'] {
    return this.nativeElement.secondary;
  }

  /** Controls whether the tab indicator is rendered on the opposite side of the tab. */
  @Input({ transform: booleanAttribute })
  public set inverted(value: TabComponentCustomElement['inverted']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.inverted = value;
    });
  }
  public get inverted(): TabComponentCustomElement['inverted'] {
    return this.nativeElement.inverted;
  }

  /** Controls whether the tab can be closed with the delete key. */
  @Input({ transform: booleanAttribute })
  public set closable(value: TabComponentCustomElement['closable']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.closable = value;
    });
  }
  public get closable(): TabComponentCustomElement['closable'] {
    return this.nativeElement.closable;
  }

  public activate(...args: Parameters<TabComponentCustomElement['activate']>): ReturnType<TabComponentCustomElement['activate']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.activate(...args));
  }

  constructor() {
    defineTabComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
