// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRteHeadingComponent } from '@tylertech/forge-rich-text-editor/features';

import { RteHeadingComponent } from './rte-heading.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RteHeadingComponent],
  exports: [RteHeadingComponent]
})
export class ForgeRteHeadingModule {
  constructor() {
    defineRteHeadingComponent();
  }
}
