// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineOverlayComponent } from '@tylertech/forge';

import { OverlayComponent } from './overlay.component';

@NgModule({
  imports: [CommonModule],
  declarations: [OverlayComponent],
  exports: [OverlayComponent]
})
export class ForgeOverlayModule {
  constructor() {
    defineOverlayComponent();
  }
}
