// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineDividerComponent } from '@tylertech/forge';

import { DividerComponent } from './divider.component';

@NgModule({
  imports: [CommonModule],
  declarations: [DividerComponent],
  exports: [DividerComponent]
})
export class ForgeDividerModule {
  constructor() {
    defineDividerComponent();
  }
}
