// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { DividerComponent as DividerComponentCustomElement, defineDividerComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-divider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class DividerComponent {
  protected elementRef = inject<ElementRef<DividerComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-divider element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Controls if the divider is displayed vertically or horizontally. */
  @Input({ transform: booleanAttribute })
  public set vertical(value: DividerComponentCustomElement['vertical']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.vertical = value;
    });
  }
  public get vertical(): DividerComponentCustomElement['vertical'] {
    return this.nativeElement.vertical;
  }

  constructor() {
    defineDividerComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
