// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineChipSetComponent } from '@tylertech/forge';

import { ForgeChipProxyModule } from '../chip/chip-proxy.module';
import { ChipSetComponent } from './chip-set.component';

@NgModule({
  imports: [CommonModule, ForgeChipProxyModule],
  declarations: [ChipSetComponent],
  exports: [ChipSetComponent, ForgeChipProxyModule]
})
export class ForgeChipSetModule {
  constructor() {
    defineChipSetComponent();
  }
}
