// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RadioComponent as RadioComponentCustomElement, defineRadioComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-radio',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RadioComponent {
  protected elementRef = inject<ElementRef<RadioComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-radio element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Gets/sets whether the radio is checked. */
  @Input({ transform: booleanAttribute })
  public set checked(value: RadioComponentCustomElement['checked']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.checked = value;
    });
  }
  public get checked(): RadioComponentCustomElement['checked'] {
    return this.nativeElement.checked;
  }

  /** Gets/sets whether the radio is checked by default. */
  @Input({ transform: booleanAttribute })
  public set defaultChecked(value: RadioComponentCustomElement['defaultChecked']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.defaultChecked = value;
    });
  }
  public get defaultChecked(): RadioComponentCustomElement['defaultChecked'] {
    return this.nativeElement.defaultChecked;
  }

  /** Gets/sets the value of the radio when submitted as part of a form. */
  @Input()
  public set value(value: RadioComponentCustomElement['value']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.value = value;
    });
  }
  public get value(): RadioComponentCustomElement['value'] {
    return this.nativeElement.value;
  }

  /** Controls whether the radio is dense. */
  @Input({ transform: booleanAttribute })
  public set dense(value: RadioComponentCustomElement['dense']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.dense = value;
    });
  }
  public get dense(): RadioComponentCustomElement['dense'] {
    return this.nativeElement.dense;
  }

  /** Controls whether the radio is disabled. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: RadioComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): RadioComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Controls whether the radio is required. */
  @Input({ transform: booleanAttribute })
  public set required(value: RadioComponentCustomElement['required']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.required = value;
    });
  }
  public get required(): RadioComponentCustomElement['required'] {
    return this.nativeElement.required;
  }

  /** Controls whether the radio is read-only. */
  @Input({ transform: booleanAttribute })
  public set readonly(value: RadioComponentCustomElement['readonly']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.readonly = value;
    });
  }
  public get readonly(): RadioComponentCustomElement['readonly'] {
    return this.nativeElement.readonly;
  }

  /** Controls whether the label appears before or after the radio. */
  @Input()
  public set labelPosition(value: RadioComponentCustomElement['labelPosition']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.labelPosition = value;
    });
  }
  public get labelPosition(): RadioComponentCustomElement['labelPosition'] {
    return this.nativeElement.labelPosition;
  }

  constructor() {
    defineRadioComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
