// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRadioComponent } from '@tylertech/forge';

import { RadioComponent } from './radio.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RadioComponent],
  exports: [RadioComponent]
})
export class ForgeRadioProxyModule {
  constructor() {
    defineRadioComponent();
  }
}
