// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { TabPanelComponent as TabPanelComponentCustomElement, defineTabPanelComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-tab-panel',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class TabPanelComponent {
  protected elementRef = inject<ElementRef<TabPanelComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-tab-panel element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The ID of the tab that controls this tab panel. */
  @Input()
  public set for(value: TabPanelComponentCustomElement['for']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.for = value;
    });
  }
  public get for(): TabPanelComponentCustomElement['for'] {
    return this.nativeElement.for;
  }

  /**
   * A reference to the associated tab element. This is typically set automatically based on the
   * `for` property, but can also be set directly for more dynamic use cases.
   */
  @Input()
  public set forElement(value: TabPanelComponentCustomElement['forElement']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.forElement = value;
    });
  }
  public get forElement(): TabPanelComponentCustomElement['forElement'] {
    return this.nativeElement.forElement;
  }

  /**
   * Whether the tab panel is open (visible). This is typically controlled by the associated tab,
   * but can also be set directly.
   */
  @Input({ transform: booleanAttribute })
  public set open(value: TabPanelComponentCustomElement['open']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.open = value;
    });
  }
  public get open(): TabPanelComponentCustomElement['open'] {
    return this.nativeElement.open;
  }

  /**
   * Controls how focus is managed when the tab panel is opened. When set to 'auto' focus is set to
   * the panel. Set to 'off' to disable focus management.
   */
  @Input()
  public set focusOnOpen(value: TabPanelComponentCustomElement['focusOnOpen']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.focusOnOpen = value;
    });
  }
  public get focusOnOpen(): TabPanelComponentCustomElement['focusOnOpen'] {
    return this.nativeElement.focusOnOpen;
  }

  constructor() {
    defineTabPanelComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
