// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineTabPanelComponent } from '@tylertech/forge';

import { TabPanelComponent } from './tab-panel.component';

@NgModule({
  imports: [CommonModule],
  declarations: [TabPanelComponent],
  exports: [TabPanelComponent]
})
export class ForgeTabPanelModule {
  constructor() {
    defineTabPanelComponent();
  }
}
