// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRteItalicComponent } from '@tylertech/forge-rich-text-editor/features';

import { RteItalicComponent } from './rte-italic.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RteItalicComponent],
  exports: [RteItalicComponent]
})
export class ForgeRteItalicModule {
  constructor() {
    defineRteItalicComponent();
  }
}
