// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ButtonComponent as ButtonComponentCustomElement, defineButtonComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ButtonComponent {
  protected elementRef = inject<ElementRef<ButtonComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-button element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Gets/sets the button variant. */
  @Input()
  public set variant(value: ButtonComponentCustomElement['variant']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.variant = value;
    });
  }
  public get variant(): ButtonComponentCustomElement['variant'] {
    return this.nativeElement.variant;
  }

  /** Gets/sets whether the button is pill-shaped. */
  @Input({ transform: booleanAttribute })
  public set pill(value: ButtonComponentCustomElement['pill']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.pill = value;
    });
  }
  public get pill(): ButtonComponentCustomElement['pill'] {
    return this.nativeElement.pill;
  }

  /** Gets/sets the button theme. */
  @Input()
  public set theme(value: ButtonComponentCustomElement['theme']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.theme = value;
    });
  }
  public get theme(): ButtonComponentCustomElement['theme'] {
    return this.nativeElement.theme;
  }

  /** Gets/sets whether the button is full-width. */
  @Input({ transform: booleanAttribute })
  public set fullWidth(value: ButtonComponentCustomElement['fullWidth']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.fullWidth = value;
    });
  }
  public get fullWidth(): ButtonComponentCustomElement['fullWidth'] {
    return this.nativeElement.fullWidth;
  }

  /** Gets/sets the type of button. */
  @Input()
  public set type(value: ButtonComponentCustomElement['type']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.type = value;
    });
  }
  public get type(): ButtonComponentCustomElement['type'] {
    return this.nativeElement.type;
  }

  /** Gets/sets whether the button is disabled. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: ButtonComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): ButtonComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Gets/sets whether the button is dense. */
  @Input({ transform: booleanAttribute })
  public set dense(value: ButtonComponentCustomElement['dense']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.dense = value;
    });
  }
  public get dense(): ButtonComponentCustomElement['dense'] {
    return this.nativeElement.dense;
  }

  /** Gets/sets whether to show a popover icon. */
  @Input({ transform: booleanAttribute })
  public set popoverIcon(value: ButtonComponentCustomElement['popoverIcon']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.popoverIcon = value;
    });
  }
  public get popoverIcon(): ButtonComponentCustomElement['popoverIcon'] {
    return this.nativeElement.popoverIcon;
  }

  /** Gets/sets the button name for form association. */
  @Input()
  public set name(value: ButtonComponentCustomElement['name']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.name = value;
    });
  }
  public get name(): ButtonComponentCustomElement['name'] {
    return this.nativeElement.name;
  }

  /** Gets/sets the button value for form submission. */
  @Input()
  public set value(value: ButtonComponentCustomElement['value']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.value = value;
    });
  }
  public get value(): ButtonComponentCustomElement['value'] {
    return this.nativeElement.value;
  }

  /** Indicates to the targeted element which action to take. */
  @Input()
  public set command(value: ButtonComponentCustomElement['command']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.command = value;
    });
  }
  public get command(): ButtonComponentCustomElement['command'] {
    return this.nativeElement.command;
  }

  /** Targets another element to be invoked. */
  @Input()
  public set commandFor(value: ButtonComponentCustomElement['commandFor']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.commandFor = value;
    });
  }
  public get commandFor(): ButtonComponentCustomElement['commandFor'] {
    return this.nativeElement.commandFor;
  }

  /** Targets another element to be invoked. */
  @Input()
  public set commandForElement(value: ButtonComponentCustomElement['commandForElement']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.commandForElement = value;
    });
  }
  public get commandForElement(): ButtonComponentCustomElement['commandForElement'] {
    return this.nativeElement.commandForElement;
  }

  public click(...args: Parameters<ButtonComponentCustomElement['click']>): ReturnType<ButtonComponentCustomElement['click']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.click(...args));
  }

  public focus(...args: Parameters<ButtonComponentCustomElement['focus']>): ReturnType<ButtonComponentCustomElement['focus']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.focus(...args));
  }

  constructor() {
    defineButtonComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
