// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RteBulletListComponent as RteBulletListComponentCustomElement, defineRteBulletListComponent } from '@tylertech/forge-rich-text-editor/features';

/**  */
@Component({
  selector: 'forge-rte-bullet-list',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RteBulletListComponent {
  protected elementRef = inject<ElementRef<RteBulletListComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-bullet-list element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the bullet list button. */
  @Input()
  public set label(value: RteBulletListComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RteBulletListComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  public get extensions(): RteBulletListComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRteBulletListComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
