// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input, inject } from '@angular/core';
import { SplitViewComponent as SplitViewComponentCustomElement, defineSplitViewComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-split-view',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class SplitViewComponent {
  protected elementRef = inject<ElementRef<SplitViewComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-split-view element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether child split view panels are laid out and resize horizontally or vertically. */
  @Input()
  public set orientation(value: SplitViewComponentCustomElement['orientation']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.orientation = value;
    });
  }
  public get orientation(): SplitViewComponentCustomElement['orientation'] {
    return this.nativeElement.orientation;
  }

  /** Whether child split view panels have resize interactions disabled or enabled. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: SplitViewComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): SplitViewComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Whether child split view panels can be closed via keyboard interaction. */
  @Input({ transform: booleanAttribute })
  public set allowClose(value: SplitViewComponentCustomElement['allowClose']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.allowClose = value;
    });
  }
  public get allowClose(): SplitViewComponentCustomElement['allowClose'] {
    return this.nativeElement.allowClose;
  }

  /** Whether child split view panels automatically close when they reach a size of 0. */
  @Input({ transform: booleanAttribute })
  public set autoClose(value: SplitViewComponentCustomElement['autoClose']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.autoClose = value;
    });
  }
  public get autoClose(): SplitViewComponentCustomElement['autoClose'] {
    return this.nativeElement.autoClose;
  }

  /** The size at which panels auto close. */
  @Input({ transform: numberAttribute })
  public set autoCloseThreshold(value: SplitViewComponentCustomElement['autoCloseThreshold']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.autoCloseThreshold = value;
    });
  }
  public get autoCloseThreshold(): SplitViewComponentCustomElement['autoCloseThreshold'] {
    return this.nativeElement.autoCloseThreshold;
  }

  /** Arranges split view panels to avoid overlapping during animations. */
  public layerSlottedPanels(
    ...args: Parameters<SplitViewComponentCustomElement['layerSlottedPanels']>
  ): ReturnType<SplitViewComponentCustomElement['layerSlottedPanels']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.layerSlottedPanels(...args));
  }

  /** Removes presentation data set during an animation. */
  public unlayerSlottedPanels(
    ...args: Parameters<SplitViewComponentCustomElement['unlayerSlottedPanels']>
  ): ReturnType<SplitViewComponentCustomElement['unlayerSlottedPanels']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.unlayerSlottedPanels(...args));
  }

  /** Updates the provided characteristics of each slotted panel. */
  public update(...args: Parameters<SplitViewComponentCustomElement['update']>): ReturnType<SplitViewComponentCustomElement['update']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.update(...args));
  }

  /** Resizes panels within the split view to avoid overflow. */
  public refit(...args: Parameters<SplitViewComponentCustomElement['refit']>): ReturnType<SplitViewComponentCustomElement['refit']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.refit(...args));
  }

  constructor() {
    defineSplitViewComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
