// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRteBoldComponent } from '@tylertech/forge-rich-text-editor/features';

import { RteBoldComponent } from './rte-bold.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RteBoldComponent],
  exports: [RteBoldComponent]
})
export class ForgeRteBoldModule {
  constructor() {
    defineRteBoldComponent();
  }
}
