// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { BreadcrumbItemComponent as BreadcrumbItemComponentCustomElement, defineBreadcrumbItemComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-breadcrumb-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class BreadcrumbItemComponent {
  protected elementRef = inject<ElementRef<BreadcrumbItemComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-breadcrumb-item element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The URL that the anchor links to. */
  @Input()
  public set href(value: BreadcrumbItemComponentCustomElement['href']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.href = value;
    });
  }
  public get href(): BreadcrumbItemComponentCustomElement['href'] {
    return this.nativeElement.href;
  }

  /** Whether this item represents the current page. Replaces the anchor with a non-interactive element. */
  @Input({ transform: booleanAttribute })
  public set current(value: BreadcrumbItemComponentCustomElement['current']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.current = value;
    });
  }
  public get current(): BreadcrumbItemComponentCustomElement['current'] {
    return this.nativeElement.current;
  }

  /** Whether this item represents the home page. Renders a home icon when set to true. */
  @Input({ transform: booleanAttribute })
  public set home(value: BreadcrumbItemComponentCustomElement['home']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.home = value;
    });
  }
  public get home(): BreadcrumbItemComponentCustomElement['home'] {
    return this.nativeElement.home;
  }

  constructor() {
    defineBreadcrumbItemComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
