// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineBreadcrumbItemComponent } from '@tylertech/forge';

import { BreadcrumbItemComponent } from './breadcrumb-item.component';

@NgModule({
  imports: [CommonModule],
  declarations: [BreadcrumbItemComponent],
  exports: [BreadcrumbItemComponent]
})
export class ForgeBreadcrumbItemModule {
  constructor() {
    defineBreadcrumbItemComponent();
  }
}
