// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineKeyItemComponent } from '@tylertech/forge';

import { KeyItemComponent } from './key-item.component';

@NgModule({
  imports: [CommonModule],
  declarations: [KeyItemComponent],
  exports: [KeyItemComponent]
})
export class ForgeKeyItemModule {
  constructor() {
    defineKeyItemComponent();
  }
}
