// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineLinearProgressComponent } from '@tylertech/forge';

import { LinearProgressComponent } from './linear-progress.component';

@NgModule({
  imports: [CommonModule],
  declarations: [LinearProgressComponent],
  exports: [LinearProgressComponent]
})
export class ForgeLinearProgressModule {
  constructor() {
    defineLinearProgressComponent();
  }
}
