// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RteUnderlineComponent as RteUnderlineComponentCustomElement, defineRteUnderlineComponent } from '@tylertech/forge-rich-text-editor/features';

/**  */
@Component({
  selector: 'forge-rte-underline',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RteUnderlineComponent {
  protected elementRef = inject<ElementRef<RteUnderlineComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-underline element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the underline button. */
  @Input()
  public set label(value: RteUnderlineComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RteUnderlineComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  public get extensions(): RteUnderlineComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRteUnderlineComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
