// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineSelectComponent } from '@tylertech/forge';

import { ForgeOptionModule } from '../option/option.module';
import { SelectComponent } from './select.component';

@NgModule({
  imports: [CommonModule, ForgeOptionModule],
  declarations: [SelectComponent],
  exports: [SelectComponent, ForgeOptionModule]
})
export class ForgeSelectProxyModule {
  constructor() {
    defineSelectComponent();
  }
}
