// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineColorPickerComponent } from '@tylertech/forge';

import { ColorPickerComponent } from './color-picker.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ColorPickerComponent],
  exports: [ColorPickerComponent]
})
export class ForgeColorPickerModule {
  constructor() {
    defineColorPickerComponent();
  }
}
