// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAppLauncherComponent } from '@tylertech/forge/app-launcher';

import { ForgeAppLauncherLinkModule } from '../app-launcher-link/app-launcher-link.module';
import { AppLauncherComponent } from './app-launcher.component';

@NgModule({
  imports: [CommonModule, ForgeAppLauncherLinkModule],
  declarations: [AppLauncherComponent],
  exports: [AppLauncherComponent, ForgeAppLauncherLinkModule]
})
export class ForgeAppLauncherModule {
  constructor() {
    defineAppLauncherComponent();
  }
}
