// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAutocompleteComponent } from '@tylertech/forge';

import { AutocompleteComponent } from './autocomplete.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AutocompleteComponent],
  exports: [AutocompleteComponent]
})
export class ForgeAutocompleteProxyModule {
  constructor() {
    defineAutocompleteComponent();
  }
}
