// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineProfileLinkComponent } from '@tylertech/forge/user-profile/profile-link';

import { ProfileLinkComponent } from './profile-link.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ProfileLinkComponent],
  exports: [ProfileLinkComponent]
})
export class ForgeProfileLinkModule {
  constructor() {
    defineProfileLinkComponent();
  }
}
