// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ProfileLinkComponent as ProfileLinkComponentCustomElement, defineProfileLinkComponent } from '@tylertech/forge/user-profile/profile-link';

/**  */
@Component({
  selector: 'forge-profile-link',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ProfileLinkComponent {
  protected elementRef = inject<ElementRef<ProfileLinkComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-profile-link element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineProfileLinkComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
