// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineCircularProgressComponent } from '@tylertech/forge';

import { CircularProgressComponent } from './circular-progress.component';

@NgModule({
  imports: [CommonModule],
  declarations: [CircularProgressComponent],
  exports: [CircularProgressComponent]
})
export class ForgeCircularProgressModule {
  constructor() {
    defineCircularProgressComponent();
  }
}
