// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { CountCardComponent as CountCardComponentCustomElement, defineCountCardComponent } from '@tylertech/forge/count-card';

/**  */
@Component({
  selector: 'forge-count-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class CountCardComponent {
  protected elementRef = inject<ElementRef<CountCardComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-count-card element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The theme variant applied to the card. */
  @Input()
  public set theme(value: CountCardComponentCustomElement['theme']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.theme = value;
    });
  }
  public get theme(): CountCardComponentCustomElement['theme'] {
    return this.nativeElement.theme;
  }

  /** Whether to hide the card border. */
  @Input({ transform: booleanAttribute })
  public set noBorder(value: CountCardComponentCustomElement['noBorder']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.noBorder = value;
    });
  }
  public get noBorder(): CountCardComponentCustomElement['noBorder'] {
    return this.nativeElement.noBorder;
  }

  constructor() {
    defineCountCardComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
