// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineCountCardComponent } from '@tylertech/forge/count-card';

import { CountCardComponent } from './count-card.component';

@NgModule({
  imports: [CommonModule],
  declarations: [CountCardComponent],
  exports: [CountCardComponent]
})
export class ForgeCountCardModule {
  constructor() {
    defineCountCardComponent();
  }
}
