// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineSplitButtonComponent } from '@tylertech/forge';

import { SplitButtonComponent } from './split-button.component';

@NgModule({
  imports: [CommonModule],
  declarations: [SplitButtonComponent],
  exports: [SplitButtonComponent]
})
export class ForgeSplitButtonModule {
  constructor() {
    defineSplitButtonComponent();
  }
}
