// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineScaffoldComponent } from '@tylertech/forge';

import { ScaffoldComponent } from './scaffold.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ScaffoldComponent],
  exports: [ScaffoldComponent]
})
export class ForgeScaffoldModule {
  constructor() {
    defineScaffoldComponent();
  }
}
