// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextRendererComponent } from '@tylertech/forge-rich-text-editor';

import { RichTextRendererComponent } from './rich-text-renderer.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextRendererComponent],
  exports: [RichTextRendererComponent]
})
export class ForgeRichTextRendererModule {
  constructor() {
    defineRichTextRendererComponent();
  }
}
