// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RichTextRendererComponent as RichTextRendererComponentCustomElement, defineRichTextRendererComponent } from '@tylertech/forge-rich-text-editor';

/**  */
@Component({
  selector: 'forge-rich-text-renderer',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextRendererComponent {
  protected elementRef = inject<ElementRef<RichTextRendererComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rich-text-renderer element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The content to render in ProseMirror JSON format. Must be set as a property; it is not settable via attribute. */
  @Input()
  public set content(value: RichTextRendererComponentCustomElement['content']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.content = value;
    });
  }
  public get content(): RichTextRendererComponentCustomElement['content'] {
    return this.nativeElement.content;
  }

  constructor() {
    defineRichTextRendererComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
