// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { KeyComponent as KeyComponentCustomElement, defineKeyComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-key',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class KeyComponent {
  protected elementRef = inject<ElementRef<KeyComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-key element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineKeyComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
