// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { SkeletonComponent as SkeletonComponentCustomElement, defineSkeletonComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-skeleton',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class SkeletonComponent {
  protected elementRef = inject<ElementRef<SkeletonComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-skeleton element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Applies form field styles to the skeleton. */
  @Input({ transform: booleanAttribute })
  public set formField(value: SkeletonComponentCustomElement['formField']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.formField = value;
    });
  }
  public get formField(): SkeletonComponentCustomElement['formField'] {
    return this.nativeElement.formField;
  }

  /** Applies button styles to the skeleton. */
  @Input({ transform: booleanAttribute })
  public set button(value: SkeletonComponentCustomElement['button']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.button = value;
    });
  }
  public get button(): SkeletonComponentCustomElement['button'] {
    return this.nativeElement.button;
  }

  /** Applies chip styles to the skeleton. */
  @Input({ transform: booleanAttribute })
  public set chip(value: SkeletonComponentCustomElement['chip']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.chip = value;
    });
  }
  public get chip(): SkeletonComponentCustomElement['chip'] {
    return this.nativeElement.chip;
  }

  /** Applies list item styles to the skeleton. */
  @Input({ transform: booleanAttribute })
  public set listItem(value: SkeletonComponentCustomElement['listItem']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.listItem = value;
    });
  }
  public get listItem(): SkeletonComponentCustomElement['listItem'] {
    return this.nativeElement.listItem;
  }

  /** Applies text styles to the skeleton. */
  @Input({ transform: booleanAttribute })
  public set text(value: SkeletonComponentCustomElement['text']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.text = value;
    });
  }
  public get text(): SkeletonComponentCustomElement['text'] {
    return this.nativeElement.text;
  }

  /** Applies avatar styles to the skeleton. */
  @Input({ transform: booleanAttribute })
  public set avatar(value: SkeletonComponentCustomElement['avatar']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.avatar = value;
    });
  }
  public get avatar(): SkeletonComponentCustomElement['avatar'] {
    return this.nativeElement.avatar;
  }

  /** Applies stretch styles to the skeleton. */
  @Input({ transform: booleanAttribute })
  public set stretch(value: SkeletonComponentCustomElement['stretch']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.stretch = value;
    });
  }
  public get stretch(): SkeletonComponentCustomElement['stretch'] {
    return this.nativeElement.stretch;
  }

  constructor() {
    defineSkeletonComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
