// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineButtonToggleComponent } from '@tylertech/forge';

import { ButtonToggleComponent } from './button-toggle.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ButtonToggleComponent],
  exports: [ButtonToggleComponent]
})
export class ForgeButtonToggleProxyModule {
  constructor() {
    defineButtonToggleComponent();
  }
}
