// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRteStandardToolsComponent } from '@tylertech/forge-rich-text-editor/features';

import { RteStandardToolsComponent } from './rte-standard-tools.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RteStandardToolsComponent],
  exports: [RteStandardToolsComponent]
})
export class ForgeRteStandardToolsModule {
  constructor() {
    defineRteStandardToolsComponent();
  }
}
