// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RteOrderedListComponent as RteOrderedListComponentCustomElement, defineRteOrderedListComponent } from '@tylertech/forge-rich-text-editor/features';

/**  */
@Component({
  selector: 'forge-rte-ordered-list',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RteOrderedListComponent {
  protected elementRef = inject<ElementRef<RteOrderedListComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-ordered-list element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the ordered list button. */
  @Input()
  public set label(value: RteOrderedListComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RteOrderedListComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  public get extensions(): RteOrderedListComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRteOrderedListComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
