// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { RteHeadingComponent as RteHeadingComponentCustomElement, defineRteHeadingComponent } from '@tylertech/forge-rich-text-editor/features';

/**  */
@Component({
  selector: 'forge-rte-heading',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RteHeadingComponent {
  protected elementRef = inject<ElementRef<RteHeadingComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-heading element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the heading 1 button. */
  @Input()
  public set h1Label(value: RteHeadingComponentCustomElement['h1Label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.h1Label = value;
    });
  }
  public get h1Label(): RteHeadingComponentCustomElement['h1Label'] {
    return this.nativeElement.h1Label;
  }

  /** The accessible label for the heading 2 button. */
  @Input()
  public set h2Label(value: RteHeadingComponentCustomElement['h2Label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.h2Label = value;
    });
  }
  public get h2Label(): RteHeadingComponentCustomElement['h2Label'] {
    return this.nativeElement.h2Label;
  }

  /** The accessible label for the heading 3 button. */
  @Input()
  public set h3Label(value: RteHeadingComponentCustomElement['h3Label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.h3Label = value;
    });
  }
  public get h3Label(): RteHeadingComponentCustomElement['h3Label'] {
    return this.nativeElement.h3Label;
  }

  public get extensions(): RteHeadingComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRteHeadingComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
