// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRadioGroupComponent } from '@tylertech/forge';

import { ForgeRadioProxyModule } from '../radio/radio-proxy.module';
import { RadioGroupComponent } from './radio-group.component';

@NgModule({
  imports: [CommonModule, ForgeRadioProxyModule],
  declarations: [RadioGroupComponent],
  exports: [RadioGroupComponent, ForgeRadioProxyModule]
})
export class ForgeRadioGroupModule {
  constructor() {
    defineRadioGroupComponent();
  }
}
