// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineProcessStepComponent } from '@tylertech/forge';

import { ProcessStepComponent } from './process-step.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ProcessStepComponent],
  exports: [ProcessStepComponent]
})
export class ForgeProcessStepModule {
  constructor() {
    defineProcessStepComponent();
  }
}
