// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ProcessStepComponent as ProcessStepComponentCustomElement, defineProcessStepComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-process-step',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ProcessStepComponent {
  protected elementRef = inject<ElementRef<ProcessStepComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-process-step element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The state of the step within the process. */
  @Input()
  public set state(value: ProcessStepComponentCustomElement['state']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.state = value;
    });
  }
  public get state(): ProcessStepComponentCustomElement['state'] {
    return this.nativeElement.state;
  }

  /**
   * The URL that the step links to. When set, the step renders a link instead of a button. This is
   * ignored when the stepper is read-only.
   */
  @Input()
  public set href(value: ProcessStepComponentCustomElement['href']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.href = value;
    });
  }
  public get href(): ProcessStepComponentCustomElement['href'] {
    return this.nativeElement.href;
  }

  /**
   * Whether the step is disabled. A disabled step keeps the marker of its state, is dimmed, and
   * ignores interaction.
   */
  @Input({ transform: booleanAttribute })
  public set disabled(value: ProcessStepComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): ProcessStepComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  public get touched(): ProcessStepComponentCustomElement['touched'] {
    return this.nativeElement.touched;
  }

  public get labelText(): ProcessStepComponentCustomElement['labelText'] {
    return this.nativeElement.labelText;
  }

  constructor() {
    defineProcessStepComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
